apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  selector:
    app: minio
  ports:
    - name: minio-api
      protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 30999
    - name: minio-webui
      protocol: TCP
      port: 32873
      targetPort: 32873
      nodePort: 31000
  type: NodePort
