DEFAULT_VAULT_DWELLERS_NUMBER = 3
DEFAULT_STORAGE_CAPACITY = 100
MAX_BOTTLE_CAPS = 999_999
DWELLER_GROW_UP_TIME = 30 * 60

POWER_CONSUMPTION_MULTIPLIER, FOOD_CONSUMPTION_MULTIPLIER, WATER_CONSUMPTION_MULTIPLIER = (10, 10, 10)