/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BuildModeButton: typeof import('./src/components/common/BuildModeButton.vue')['default']
    DwellerChat: typeof import('./src/components/chat/DwellerChat.vue')['default']
    DwellerChatPage: typeof import('./src/components/chat/DwellerChatPage.vue')['default']
    DwellersSlideOver: typeof import('./src/components/layout/DwellersSlideOver.vue')['default']
    EmptyCell: typeof import('./src/components/rooms/EmptyCell.vue')['default']
    LoginForm: typeof import('./src/components/auth/LoginForm.vue')['default']
    PipBoyMenu: typeof import('./src/components/layout/PipBoyMenu.vue')['default']
    RegisterForm: typeof import('./src/components/auth/RegisterForm.vue')['default']
    ResourceBar: typeof import('./src/components/common/ResourceBar.vue')['default']
    RoomGrid: typeof import('./src/components/rooms/RoomGrid.vue')['default']
    RoomItem: typeof import('./src/components/rooms/RoomItem.vue')['default']
    RoomMenu: typeof import('./src/components/rooms/RoomMenu.vue')['default']
    RoomMenuItem: typeof import('./src/components/rooms/RoomMenuItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UAlert: typeof import('./node_modules/.pnpm/@nuxt+ui@3.3.7_@babel+parse_33c7f8383afc07dad69590e34ee2ccf6/node_modules/@nuxt/ui/dist/runtime/components/Alert.vue')['default']
    UBadge: typeof import('./node_modules/.pnpm/@nuxt+ui@3.3.7_@babel+parse_33c7f8383afc07dad69590e34ee2ccf6/node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./node_modules/.pnpm/@nuxt+ui@3.3.7_@babel+parse_33c7f8383afc07dad69590e34ee2ccf6/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./node_modules/.pnpm/@nuxt+ui@3.3.7_@babel+parse_33c7f8383afc07dad69590e34ee2ccf6/node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UIcon: typeof import('./node_modules/.pnpm/@nuxt+ui@3.3.7_@babel+parse_33c7f8383afc07dad69590e34ee2ccf6/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./node_modules/.pnpm/@nuxt+ui@3.3.7_@babel+parse_33c7f8383afc07dad69590e34ee2ccf6/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UModal: typeof import('./node_modules/.pnpm/@nuxt+ui@3.3.7_@babel+parse_33c7f8383afc07dad69590e34ee2ccf6/node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    UProgress: typeof import('./node_modules/.pnpm/@nuxt+ui@3.3.7_@babel+parse_33c7f8383afc07dad69590e34ee2ccf6/node_modules/@nuxt/ui/dist/runtime/components/Progress.vue')['default']
    USelectMenu: typeof import('./node_modules/.pnpm/@nuxt+ui@3.3.7_@babel+parse_33c7f8383afc07dad69590e34ee2ccf6/node_modules/@nuxt/ui/dist/runtime/components/SelectMenu.vue')['default']
    USlideover: typeof import('./node_modules/.pnpm/@nuxt+ui@3.3.7_@babel+parse_33c7f8383afc07dad69590e34ee2ccf6/node_modules/@nuxt/ui/dist/runtime/components/Slideover.vue')['default']
    UTabs: typeof import('./node_modules/.pnpm/@nuxt+ui@3.3.7_@babel+parse_33c7f8383afc07dad69590e34ee2ccf6/node_modules/@nuxt/ui/dist/runtime/components/Tabs.vue')['default']
    VaultCreationForm: typeof import('./src/components/vault/VaultCreationForm.vue')['default']
    VaultHeader: typeof import('./src/components/layout/VaultHeader.vue')['default']
    VaultLayout: typeof import('./src/components/layout/VaultLayout.vue')['default']
    VaultList: typeof import('./src/components/vault/VaultList.vue')['default']
    VaultSwitcherModal: typeof import('./src/components/layout/VaultSwitcherModal.vue')['default']
  }
}
