version: '3.9'

# Podman Compose configuration for Fallout Shelter API
# Compatible with podman-compose and can replace docker-compose
# Usage: podman-compose up -d

services:
  db:
    image: docker.io/library/postgres:18-alpine
    restart: always
    env_file: ".env"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      # Enable UUID v7 extension on startup
      - POSTGRES_INITDB_ARGS=--locale=C --encoding=UTF8

  fastapi:
    container_name: fastapi
    build:
      context: ./backend
    restart: always
    env_file: ".env"
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_started
    ports:
      - "8000:8000"
    command: "sh -c 'alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000'"
    volumes:
      - ./app:/code/app

  vuejs:
    container_name: vuejs
    build:
      context: ./frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app

  redis:
    image: docker.io/library/redis:alpine
    restart: always
    env_file: ".env"
    expose:
      - 6379
    ports:
      - "6379:6379"

  celery_worker:
    container_name: celery_worker
    build:
      context: ./backend
    restart: always
    env_file: ".env"
    depends_on:
      - db
      - redis
    command: "celery -A app.core.celery worker -l info"

  celery_beat:
    container_name: celery_beat
    build:
      context: ./backend
    restart: always
    env_file: ".env"
    depends_on:
      - db
      - redis
    command: "celery -A app.core.celery beat -l info"

  flower:
    image: docker.io/mher/flower:latest
    restart: always
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    ports:
      - "5555:5555"
    depends_on:
      - celery_worker

  minio:
    image: docker.io/minio/minio
    container_name: minio
    env_file:
      - .env
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  mailhog:
    image: docker.io/mailhog/mailhog:latest
    container_name: mailhog
    restart: always
    ports:
      - "1025:1025"  # SMTP server
      - "8025:8025"  # Web UI
    environment:
      - MH_STORAGE=maildir
      - MH_MAILDIR_PATH=/maildir
    volumes:
      - mailhog_data:/maildir

volumes:
  postgres-data:
  minio_data:
  mailhog_data:
