"""Outfit name to apparel image mapping.

Centralizes the mapping between in-game outfit names and their static image
assets. Unmapped outfits fall back to the generic equipment icon in the UI.
"""

from pathlib import Path

# Maps canonical lower-cased outfit names to the actual filename in
# backend/app/static/apparel_images/. Keep this sorted alphabetically by key.
OUTFIT_NAME_TO_IMAGE_FILE: dict[str, str] = {
    "abraham's relaxedwear": "FOS Formal Wear.png",
    "accountant outfit": "FOS Accountant outfit.png",
    "action wedding dress": "FOS Action wedding dress.png",
    "advanced institute jumper": "FOS Advanced Institute jumper.png",
    "advanced jumpsuit": "FOS Advanced jumpsuit.png",
    "advanced lab coat": "FOS Advanced lab coat.png",
    "advanced radiation suit": "FOS Advanced radiation suit.png",
    "agent provocateur": "FOS Agent provocateur.png",
    "alien space suit": "FOS Alien space suit.png",
    "armored vault suit": "FOS Armored Vault Suit.png",
    "autumn's uniform": "FOS Autumn Uniform.png",
    "baseball uniform": "FOS Baseball uniform.png",
    "battle armor": "FOS Battle armor.png",
    "bespoke attire": "FOS Bespoke attire.png",
    "bittercup's outfit": "FOS Bittercup Outfit.png",
    "bos casual": "FOS BOS casual.png",
    "bos paladin jacket": "FOS BoS paladin jacket.png",
    "bos uniform": "FOS BoS uniform.png",
    "bounty hunter gear": "FOS Bounty hunter gear.png",
    "business suit": "FOS Business suit.png",
    "clergy outfit": "FOS Clergy outfit.png",
    "combat armor": "FOS Combat armor.png",
    "comedian outfit": "FOS Comedian outfit.png",
    "commander fatigues": "FOS Commander fatigues.png",
    "commander uniform": "FOS Commander uniform.png",
    "confessor cromwell's rags": "FOS Clergy Outfit.png",
    "country girl": "FOS Country girl.png",
    "courser uniform": "FOS Courser uniform.png",
    "death's jacket": "FOS Death's jacket.png",
    "doo-wop singer": "FOS Doo-wop singer.png",
    "drag racer": "FOS Drag racer.png",
    "elder robe": "FOS Elder Robe.png",
    "elf outfit": "FOS Elf outfit.png",
    "enclave officer uniform": "FOS Enclave officer uniform.png",
    "enclave power armor": "FOS Enclave power armor.png",
    "enclave security outfit": "FOS Enclave security outfit.png",
    "engineer outfit": "FOS Engineer outfit.png",
    "eulogy jones' suit": "FOS Eulogy Outfit.png",
    "expert bos uniform": "FOS Expert BoS uniform.png",
    "expert flight suit": "FOS Expert flight suit.png",
    "expert institute jumper": "FOS Expert Institute jumper.png",
    "expert jumpsuit": "FOS Expert jumpsuit.png",
    "expert lab coat": "FOS Expert lab coat.png",
    "expert radiation suit": "FOS Expert radiation suit.png",
    "famine's vestment": "FOS Famine's vestment.png",
    "fancy formal wear": "FOS Fancy formal wear.png",
    "firefighter suit": "FOS Engineer Armor.png",
    "firefighter suit, rad helmet": "FOS Rad Suit.png",
    "flight suit": "FOS Flight suit.png",
    "formal wear": "FOS Formal wear.png",
    "ghost costume": "FOS Ghost costume.png",
    "greaser outfit": "FOS Greaser outfit.png",
    "handyman jumpsuit": "FOS Handyman jumpsuit.png",
    "hank's power armor": "FOS Hank's power armor.png",
    "hazmat suit": "FOS Rad Suit.png",
    "heavy battle armor": "FOS Heavy battle armor.png",
    "heavy combat armor": "FOS Heavy combat armor.png",
    "heavy leather armor": "FOS Heavy leather armor.png",
    "heavy merc gear": "FOS Heavy merc gear.png",
    "heavy metal armor": "FOS Heavy metal armor.png",
    "heavy raider armor": "FOS Heavy raider armor.png",
    "heavy synth armor": "FOS Combat Armor.png",
    "heavy vault suit": "FOS Armored Vault Suit.png",
    "heavy wasteland gear": "FOS Heavy wasteland gear.png",
    "horror fan outfit": "FOS Horror fan outfit.png",
    "incognito leisurewear": "FOS Incognito leisurewear.png",
    "initiate robe": "FOS Initiate robe.png",
    "jailhouse rocker": "FOS Jailhouse Rocker.png",
    "junior officer uniform": "FOS Junior officer uniform.png",
    "kellogg's armor": "FOS Kellogg's armor.png",
    "knight armor": "FOS Knight armor.png",
    "lab coat": "FOS Lab coat.png",
    "leather armor": "FOS Leather Armor.png",
    "legate armor": "FOS Legate armor.png",
    "librarian outfit": "FOS Librarian outfit.png",
    "lifeguard outfit": "FOS Lifeguard outfit.png",
    "lucky formal wear": "FOS Lucky formal wear.png",
    "lucky nightwear": "FOS Lucky nightwear.png",
    "lucy's vault suit": "FOS Lucy's vault suit.png",
    "ma june jacket": "FOS Ma June jacket.png",
    "maximus's jacket": "FOS Maximus's jacket.png",
    "mayor outfit": "FOS Mayor outfit.png",
    "mechanic jumpsuit": "FOS Handyman Outfit.png",
    "medieval ruler outfit": "FOS Medieval ruler outfit.png",
    "merc gear": "FOS Merc gear.png",
    "military fatigues": "FOS Military fatigues.png",
    "minuteman uniform": "FOS Minuteman uniform.png",
    "mojave wasteland survivor": "FOS Mojave wasteland survivor.png",
    "moldaver's armor": "FOS Moldaver's armor.png",
    "motorcycle jacket": "FOS Motorcycle jacket.png",
    "movie fan outfit": "FOS Movie fan outfit.png",
    "mr. house's suit": "FOS Mr. House's suit.png",
    "mutant hunter gear": "FOS Mutant hunter gear.png",
    "naughty nightwear": "FOS Naughty nightwear.png",
    "ncr power armor": "FOS NCR power armor.png",
    "ncr ranger outfit": "FOS Sheriff Duster.png",
    "nightwear": "FOS Nightwear.png",
    "ninja outfit": "FOS Ninja outfit.png",
    "nobility outfit": "FOS Nobility outfit.png",
    "officer fatigues": "FOS Officer fatigues.png",
    "officer uniform": "FOS Officer uniform.png",
    "original santa suit": "FOS Original Santa suit.png",
    "orion's explorer gear": "FOS Orion's explorer gear.png",
    "paladin danse's power armor": "FOS Paladin Danse's power armor.png",
    "pestilence's plating": "FOS Pestilence's plating.png",
    "pilgrim outfit": "FOS Pilgrim outfit.png",
    "pioneer overseer suit": "FOS Pioneer overseer suit.png",
    "piper's outfit": "FOS Piper's outfit.png",
    "polka dot sundress": "FOS Polka dot sundress.png",
    "post-war casanova": "FOS Post-War Casanova.png",
    "pre-war suburbanite": "FOS Pre-War suburbanite.png",
    "prewar cowboy costume": "FOS Prewar cowboy costume.png",
    "professor outfit": "FOS Professor outfit.png",
    "radiation suit": "FOS Radiation suit.png",
    "raider armor": "FOS Raider armor.png",
    "regs' dirty black suit": "FOS Regs' dirty black suit.png",
    "republic robes": "FOS Republic robes.png",
    "robco factory uniform": "FOS RobCo factory uniform.png",
    "robco r&d suit": "FOS Labcoat.png",
    "robot armor": "FOS Engineer Armor.png",
    "rural schoolmarm": "FOS Rural schoolmarm.png",
    "santa suit": "FOS Santa suit.png",
    "scarred power armor": "FOS Scarred power armor.png",
    "sci-fi fan outfit": "FOS Sci-fi fan outfit.png",
    "scribe robe": "FOS Scribe robe.png",
    "scribe rothchild's robe": "FOS Scribe Rothchild's robe.png",
    "sheriff's duster": "FOS Sheriff's duster.png",
    "skeleton costume": "FOS Skeleton costume.png",
    "sleazy suit": "FOS Sleazy suit.png",
    "sleek suit": "FOS Sleek suit.png",
    "soda fountain dress": "FOS Soda fountain dress.png",
    "soldier uniform": "FOS Soldier uniform.png",
    "sports fan outfit": "FOS Sports fan outfit.png",
    "spring casualwear": "FOS Spring casualwear.png",
    "sturdy battle armor": "FOS Sturdy battle armor.png",
    "sturdy combat armor": "FOS Sturdy combat armor.png",
    "sturdy leather armor": "FOS Sturdy leather armor.png",
    "sturdy merc gear": "FOS Sturdy merc gear.png",
    "sturdy metal armor": "FOS Sturdy metal armor.png",
    "sturdy raider armor": "FOS Sturdy raider armor.png",
    "sturdy vault suit": "FOS Vault Suit.png",
    "sturdy wasteland gear": "FOS Sturdy wasteland gear.png",
    "surgeon outfit": "FOS Surgeon outfit.png",
    "survivor armor": "FOS Survivor armor.png",
    "swimsuit": "FOS Swimsuit.png",
    "swing dress": "FOS Swing dress.png",
    "t-45a power armor": "FOS T45 Outfit.png",
    "t-45d power armor": "FOS T45 Outfit.png",
    "t-45f power armor": "FOS T45 Outfit.png",
    "t-51a power armor": "FOS T51 Outfit.png",
    "t-51b power armor": "FOS T51 Outfit.png",
    "t-51d power armor": "FOS T51 Outfit.png",
    "t-51f power armor": "FOS T51 Outfit.png",
    "t-60a power armor": "FOS T60 Outfit.png",
    "t-60d power armor": "FOS T60 Outfit.png",
    "t-60f power armor": "FOS T60 Outfit.png",
    "tattered longcoat": "FOS Sheriff Duster.png",
    "tenpenny's suit": "FOS Tenpenny's suit.png",
    "the ghoul's coat": "FOS The Ghoul's coat.png",
    "three dog's outfit": "FOS Three Dog's outfit.png",
    "treasure hunter gear": "FOS Treasure hunter gear.png",
    "tunnel snakes' outfit": "FOS Tunnel Snakes' outfit.png",
    "valentine's trench coat": "FOS Valentine's trench coat.png",
    "vault 33 suit": "FOS Vault 33 suit.png",
    "vault jumpsuit": "FOS Vault Suit.png",
    "vault security outfit": "FOS Vault security outfit.png",
    "vault socialite": "FOS Vault socialite.png",
    "waitress uniform": "FOS Waitress uniform.png",
    "war's armor": "FOS War's armor.png",
    "wasteland doctor": "FOS Wasteland doctor.png",
    "wasteland gear": "FOS Wasteland gear.png",
    "wasteland medic": "FOS Wasteland medic.png",
    "wasteland surgeon": "FOS Wasteland surgeon.png",
    "wedding dress": "FOS Wedding dress.png",
    "wilzig's travelwear": "FOS Wilzig's travelwear.png",
    "wrestler outfit": "FOS Wrestler outfit.png",
    "x-01 mk i power armor": "FOS X-01 Outfit.png",
    "x-01 mk iv power armor": "FOS X-01 Outfit.png",
    "x-01 mk vi power armor": "FOS X-01 Outfit.png",
}

_APPAREL_IMAGE_DIR = Path(__file__).parent.parent / "static" / "apparel_images"


def get_outfit_image_url(outfit_name: str | None) -> str | None:
    """Return the static image URL for an outfit, if a mapped asset exists.

    The lookup is case-insensitive and ignores leading/trailing whitespace.
    Returns ``None`` when the outfit is unmapped or the mapped file is missing
    on disk, so callers can fall back to a generic icon.
    """
    if not outfit_name:
        return None

    key = outfit_name.strip().casefold()
    filename = OUTFIT_NAME_TO_IMAGE_FILE.get(key)
    if not filename:
        return None

    if not (_APPAREL_IMAGE_DIR / filename).exists():
        return None

    return f"/static/apparel_images/{filename}"
