"""quests

Revision ID: 871004adaf85
Revises: e1ce3046c1a1
Create Date: 2024-03-29 00:17:11.097861

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "871004adaf85"
down_revision: Union[str, None] = "e1ce3046c1a1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "questchain",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("completed", sa.Boolean(), nullable=False),
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_questchain_id"), "questchain", ["id"], unique=False)
    op.create_index(op.f("ix_questchain_title"), "questchain", ["title"], unique=False)
    op.add_column("quest", sa.Column("chain_id", sqlmodel.sql.sqltypes.GUID(), nullable=False))
    op.alter_column("quest", "completed", existing_type=sa.BOOLEAN(), nullable=False)
    op.create_foreign_key(None, "quest", "questchain", ["chain_id"], ["id"])
    op.drop_column("queststep", "order_number")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("queststep", sa.Column("order_number", sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, "quest", type_="foreignkey")
    op.alter_column("quest", "completed", existing_type=sa.BOOLEAN(), nullable=True)
    op.drop_column("quest", "chain_id")
    op.drop_index(op.f("ix_questchain_title"), table_name="questchain")
    op.drop_index(op.f("ix_questchain_id"), table_name="questchain")
    op.drop_table("questchain")
    # ### end Alembic commands ###
