"""initial

Revision ID: e1ce3046c1a1
Revises: 
Create Date: 2024-03-28 22:19:02.955469

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "e1ce3046c1a1"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "junk",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("rarity", sa.Enum("common", "rare", "legendary", name="rarity"), nullable=False),
        sa.Column("value", sa.Integer(), nullable=True),
        sa.Column(
            "junk_type",
            sa.Enum("circuitry", "leather", "adhesive", "cloth", "science", "steel", "valuables", name="junktype"),
            nullable=False,
        ),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_junk_id"), "junk", ["id"], unique=False)
    op.create_index(op.f("ix_junk_name"), "junk", ["name"], unique=True)
    op.create_table(
        "quest",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("completed", sa.Boolean(), nullable=True),
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_quest_id"), "quest", ["id"], unique=False)
    op.create_index(op.f("ix_quest_title"), "quest", ["title"], unique=False)
    op.create_table(
        "user",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=False)
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=True)
    op.create_table(
        "queststep",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("order_number", sa.Integer(), nullable=False),
        sa.Column("completed", sa.Boolean(), nullable=False),
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("quest_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["quest_id"],
            ["quest.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_queststep_id"), "queststep", ["id"], unique=False)
    op.create_index(op.f("ix_queststep_title"), "queststep", ["title"], unique=False)
    op.create_table(
        "vault",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("name", sa.Integer(), nullable=False),
        sa.Column("bottle_caps", sa.Integer(), nullable=False),
        sa.Column("happiness", sa.Integer(), nullable=False),
        sa.Column("power", sa.Integer(), nullable=False),
        sa.Column("power_max", sa.Integer(), nullable=False),
        sa.Column("food", sa.Integer(), nullable=False),
        sa.Column("food_max", sa.Integer(), nullable=False),
        sa.Column("water", sa.Integer(), nullable=False),
        sa.Column("water_max", sa.Integer(), nullable=False),
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_vault_id"), "vault", ["id"], unique=False)
    op.create_index(op.f("ix_vault_name"), "vault", ["name"], unique=False)
    op.create_table(
        "room",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "category",
            sa.Enum("capacity", "crafting", "misc", "production", "quests", "theme", "training", name="roomtype"),
            nullable=False,
        ),
        sa.Column(
            "ability",
            sa.Enum(
                "strength", "perception", "endurance", "charisma", "intelligence", "agility", "luck", name="special",
            ),
            nullable=True,
        ),
        sa.Column("population_required", sa.Integer(), nullable=True),
        sa.Column("base_cost", sa.Integer(), nullable=False),
        sa.Column("incremental_cost", sa.Integer(), nullable=False),
        sa.Column("t2_upgrade_cost", sa.Integer(), nullable=True),
        sa.Column("t3_upgrade_cost", sa.Integer(), nullable=True),
        sa.Column("output", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("size_min", sa.Integer(), nullable=False),
        sa.Column("size_max", sa.Integer(), nullable=False),
        sa.Column("tier", sa.Integer(), nullable=False),
        sa.Column("max_tier", sa.Integer(), nullable=False),
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("vault_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["vault_id"],
            ["vault.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_room_id"), "room", ["id"], unique=False)
    op.create_index(op.f("ix_room_name"), "room", ["name"], unique=False)
    op.create_table(
        "dweller",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("strength", sa.Integer(), nullable=False),
        sa.Column("perception", sa.Integer(), nullable=False),
        sa.Column("endurance", sa.Integer(), nullable=False),
        sa.Column("charisma", sa.Integer(), nullable=False),
        sa.Column("intelligence", sa.Integer(), nullable=False),
        sa.Column("agility", sa.Integer(), nullable=False),
        sa.Column("luck", sa.Integer(), nullable=False),
        sa.Column("first_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("last_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_adult", sa.Boolean(), nullable=False),
        sa.Column("gender", sa.Enum("male", "female", name="gender"), nullable=False),
        sa.Column("rarity", sa.Enum("common", "rare", "legendary", name="rarity"), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("experience", sa.Integer(), nullable=False),
        sa.Column("max_health", sa.Integer(), nullable=False),
        sa.Column("health", sa.Integer(), nullable=False),
        sa.Column("radiation", sa.Integer(), nullable=False),
        sa.Column("happiness", sa.Integer(), nullable=False),
        sa.Column("stimpack", sa.Integer(), nullable=False),
        sa.Column("radaway", sa.Integer(), nullable=False),
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("vault_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("room_id", sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["room.id"],
        ),
        sa.ForeignKeyConstraint(
            ["vault_id"],
            ["vault.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_dweller_first_name"), "dweller", ["first_name"], unique=False)
    op.create_index(op.f("ix_dweller_id"), "dweller", ["id"], unique=False)
    op.create_index(op.f("ix_dweller_last_name"), "dweller", ["last_name"], unique=False)
    op.create_table(
        "outfit",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("rarity", sa.Enum("common", "rare", "legendary", name="rarity"), nullable=False),
        sa.Column("value", sa.Integer(), nullable=True),
        sa.Column(
            "outfit_type",
            sa.Enum("common", "rare", "legendary", "power_armor", "tiered", name="outfittype"),
            nullable=True,
        ),
        sa.Column("gender", sa.Enum("male", "female", name="gender"), nullable=True),
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("dweller_id", sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["dweller_id"],
            ["dweller.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_outfit_id"), "outfit", ["id"], unique=False)
    op.create_index(op.f("ix_outfit_name"), "outfit", ["name"], unique=True)
    op.create_table(
        "weapon",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("rarity", sa.Enum("common", "rare", "legendary", name="rarity"), nullable=False),
        sa.Column("value", sa.Integer(), nullable=True),
        sa.Column("weapon_type", sa.Enum("melee", "gun", "energy", "heavy", name="weapontype"), nullable=False),
        sa.Column(
            "weapon_subtype",
            sa.Enum(
                "blunt",
                "edged",
                "pointed",
                "pistol",
                "rifle",
                "shotgun",
                "automatic",
                "explosive",
                "flamer",
                name="weaponsubtype",
            ),
            nullable=False,
        ),
        sa.Column("stat", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("damage_min", sa.Integer(), nullable=False),
        sa.Column("damage_max", sa.Integer(), nullable=False),
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("dweller_id", sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["dweller_id"],
            ["dweller.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_weapon_id"), "weapon", ["id"], unique=False)
    op.create_index(op.f("ix_weapon_name"), "weapon", ["name"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_weapon_name"), table_name="weapon")
    op.drop_index(op.f("ix_weapon_id"), table_name="weapon")
    op.drop_table("weapon")
    op.drop_index(op.f("ix_outfit_name"), table_name="outfit")
    op.drop_index(op.f("ix_outfit_id"), table_name="outfit")
    op.drop_table("outfit")
    op.drop_index(op.f("ix_dweller_last_name"), table_name="dweller")
    op.drop_index(op.f("ix_dweller_id"), table_name="dweller")
    op.drop_index(op.f("ix_dweller_first_name"), table_name="dweller")
    op.drop_table("dweller")
    op.drop_index(op.f("ix_room_name"), table_name="room")
    op.drop_index(op.f("ix_room_id"), table_name="room")
    op.drop_table("room")
    op.drop_index(op.f("ix_vault_name"), table_name="vault")
    op.drop_index(op.f("ix_vault_id"), table_name="vault")
    op.drop_table("vault")
    op.drop_index(op.f("ix_queststep_title"), table_name="queststep")
    op.drop_index(op.f("ix_queststep_id"), table_name="queststep")
    op.drop_table("queststep")
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.drop_index(op.f("ix_user_id"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_quest_title"), table_name="quest")
    op.drop_index(op.f("ix_quest_id"), table_name="quest")
    op.drop_table("quest")
    op.drop_index(op.f("ix_junk_name"), table_name="junk")
    op.drop_index(op.f("ix_junk_id"), table_name="junk")
    op.drop_table("junk")
    # ### end Alembic commands ###
