"""initial

Revision ID: a4687a3e771b
Revises: 
Create Date: 2023-05-09 00:03:13.211195

"""  # noqa: W291
import sqlalchemy as sa
import sqlmodel  # noqa: F401

from alembic import op

# revision identifiers, used by Alembic.
revision = "a4687a3e771b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_junk_name", table_name="junk")
    op.drop_table("junk")
    op.drop_index("ix_outfit_name", table_name="outfit")
    op.drop_table("outfit")
    op.drop_index("ix_queststep_title", table_name="queststep")
    op.drop_table("queststep")
    op.drop_index("ix_item_name", table_name="item")
    op.drop_table("item")
    op.drop_index("ix_weapon_name", table_name="weapon")
    op.drop_table("weapon")
    op.drop_index("ix_quest_title", table_name="quest")
    op.drop_table("quest")
    op.drop_index("ix_user_email", table_name="user")
    op.drop_index("ix_user_username", table_name="user")
    op.drop_table("user")
    op.drop_index("ix_room_name", table_name="room")
    op.drop_table("room")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "room",
        sa.Column("created_at", sa.DATETIME(), nullable=True),
        sa.Column("updated_at", sa.DATETIME(), nullable=True),
        sa.Column("name", sa.VARCHAR(length=32), nullable=False),
        sa.Column("category", sa.VARCHAR(), nullable=False),
        sa.Column("ability", sa.VARCHAR(), nullable=False),
        sa.Column("population_required", sa.INTEGER(), nullable=True),
        sa.Column("base_cost", sa.INTEGER(), nullable=False),
        sa.Column("incremental_cost", sa.INTEGER(), nullable=False),
        sa.Column("tier", sa.INTEGER(), nullable=False),
        sa.Column("max_tier", sa.INTEGER(), nullable=False),
        sa.Column("t2_upgrade_cost", sa.INTEGER(), nullable=True),
        sa.Column("t3_upgrade_cost", sa.INTEGER(), nullable=True),
        sa.Column("output", sa.INTEGER(), nullable=True),
        sa.Column("size", sa.INTEGER(), nullable=False),
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_room_name", "room", ["name"], unique=False)
    op.create_table(
        "user",
        sa.Column("created_at", sa.DATETIME(), nullable=True),
        sa.Column("updated_at", sa.DATETIME(), nullable=True),
        sa.Column("username", sa.VARCHAR(length=32), nullable=False),
        sa.Column("email", sa.VARCHAR(), nullable=True),
        sa.Column("is_active", sa.BOOLEAN(), nullable=False),
        sa.Column("is_superuser", sa.BOOLEAN(), nullable=False),
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("hashed_password", sa.VARCHAR(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_user_username", "user", ["username"], unique=False)
    op.create_index("ix_user_email", "user", ["email"], unique=False)
    op.create_table(
        "quest",
        sa.Column("created_at", sa.DATETIME(), nullable=True),
        sa.Column("updated_at", sa.DATETIME(), nullable=True),
        sa.Column("title", sa.VARCHAR(length=64), nullable=False),
        sa.Column("description", sa.VARCHAR(length=255), nullable=False),
        sa.Column("completed", sa.BOOLEAN(), nullable=True),
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_quest_title", "quest", ["title"], unique=False)
    op.create_table(
        "weapon",
        sa.Column("name", sa.VARCHAR(length=32), nullable=False),
        sa.Column("rarity", sa.VARCHAR(), nullable=False),
        sa.Column("value", sa.INTEGER(), nullable=True),
        sa.Column("weapon_type", sa.VARCHAR(), nullable=False),
        sa.Column("weapon_subtype", sa.VARCHAR(), nullable=False),
        sa.Column("stat", sa.VARCHAR(), nullable=False),
        sa.Column("damage_min", sa.INTEGER(), nullable=False),
        sa.Column("damage_max", sa.INTEGER(), nullable=False),
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_weapon_name", "weapon", ["name"], unique=False)
    op.create_table(
        "item",
        sa.Column("created_at", sa.DATETIME(), nullable=True),
        sa.Column("updated_at", sa.DATETIME(), nullable=True),
        sa.Column("name", sa.VARCHAR(length=32), nullable=False),
        sa.Column("rarity", sa.VARCHAR(), nullable=False),
        sa.Column("value", sa.INTEGER(), nullable=True),
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_item_name", "item", ["name"], unique=False)
    op.create_table(
        "queststep",
        sa.Column("title", sa.VARCHAR(length=64), nullable=False),
        sa.Column("description", sa.VARCHAR(length=255), nullable=False),
        sa.Column("order_number", sa.INTEGER(), nullable=False),
        sa.Column("completed", sa.BOOLEAN(), nullable=False),
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("quest_id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["quest_id"],
            ["quest.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_queststep_title", "queststep", ["title"], unique=False)
    op.create_table(
        "outfit",
        sa.Column("name", sa.VARCHAR(length=32), nullable=False),
        sa.Column("rarity", sa.VARCHAR(), nullable=False),
        sa.Column("value", sa.INTEGER(), nullable=True),
        sa.Column("outfit_type", sa.VARCHAR(), nullable=False),
        sa.Column("gender", sa.VARCHAR(), nullable=True),
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_outfit_name", "outfit", ["name"], unique=False)
    op.create_table(
        "junk",
        sa.Column("created_at", sa.DATETIME(), nullable=True),
        sa.Column("updated_at", sa.DATETIME(), nullable=True),
        sa.Column("name", sa.VARCHAR(length=32), nullable=False),
        sa.Column("rarity", sa.VARCHAR(), nullable=False),
        sa.Column("value", sa.INTEGER(), nullable=True),
        sa.Column("junk_type", sa.VARCHAR(), nullable=False),
        sa.Column("description", sa.VARCHAR(), nullable=False),
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_junk_name", "junk", ["name"], unique=False)
    # ### end Alembic commands ###
