"""vault_objective

Revision ID: ac34bc503518
Revises: 821eb836836e
Create Date: 2024-06-22 00:33:51.397460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ac34bc503518'
down_revision: Union[str, None] = '821eb836836e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('objective',
    sa.Column('challenge', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('reward', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_objective_challenge'), 'objective', ['challenge'], unique=False)
    op.create_index(op.f('ix_objective_id'), 'objective', ['id'], unique=False)
    op.create_table('vaultobjectiveprogresslink',
    sa.Column('vault_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('objective_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['objective_id'], ['objective.id'], ),
    sa.ForeignKeyConstraint(['vault_id'], ['vault.id'], ),
    sa.PrimaryKeyConstraint('vault_id', 'objective_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vaultobjectiveprogresslink')
    op.drop_index(op.f('ix_objective_id'), table_name='objective')
    op.drop_index(op.f('ix_objective_challenge'), table_name='objective')
    op.drop_table('objective')
    # ### end Alembic commands ###
