"""image_url

Revision ID: 4ef1bee0b4c4
Revises: 29509abe0b03
Create Date: 2024-06-15 00:41:50.796197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4ef1bee0b4c4'
down_revision: Union[str, None] = '29509abe0b03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dweller', sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('junk', sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('outfit', sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('weapon', sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weapon', 'image_url')
    op.drop_column('outfit', 'image_url')
    op.drop_column('junk', 'image_url')
    op.drop_column('dweller', 'image_url')
    # ### end Alembic commands ###
