"""capacity_and_limits

Revision ID: 5da8ad6c511e
Revises: ce261d292404
Create Date: 2024-05-20 00:33:17.187005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5da8ad6c511e'
down_revision: Union[str, None] = 'ce261d292404'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('capacity', sa.Integer(), nullable=True))
    op.add_column('vault', sa.Column('population_max', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vault', 'population_max')
    op.drop_column('room', 'capacity')
    # ### end Alembic commands ###
