"""Quests

Revision ID: 29509abe0b03
Revises: 724d6aaa2a96
Create Date: 2024-06-14 00:35:20.820582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '29509abe0b03'
down_revision: Union[str, None] = '724d6aaa2a96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questobjective',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('quest_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['quest_id'], ['quest.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questobjective_id'), 'questobjective', ['id'], unique=False)
    op.create_index(op.f('ix_questobjective_title'), 'questobjective', ['title'], unique=False)
    op.drop_index('ix_queststep_id', table_name='queststep')
    op.drop_index('ix_queststep_title', table_name='queststep')
    op.drop_table('queststep')
    op.add_column('quest', sa.Column('long_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('quest', sa.Column('short_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('quest', sa.Column('requirements', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('quest', sa.Column('rewards', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('quest', 'description')
    op.drop_column('questchain', 'description')
    op.drop_column('questchain', 'created_at')
    op.drop_column('questchain', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questchain', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('questchain', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('questchain', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('quest', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('quest', 'rewards')
    op.drop_column('quest', 'requirements')
    op.drop_column('quest', 'short_description')
    op.drop_column('quest', 'long_description')
    op.create_table('queststep',
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('quest_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['quest_id'], ['quest.id'], name='queststep_quest_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='queststep_pkey')
    )
    op.create_index('ix_queststep_title', 'queststep', ['title'], unique=False)
    op.create_index('ix_queststep_id', 'queststep', ['id'], unique=False)
    op.drop_index(op.f('ix_questobjective_title'), table_name='questobjective')
    op.drop_index(op.f('ix_questobjective_id'), table_name='questobjective')
    op.drop_table('questobjective')
    # ### end Alembic commands ###
