"""remove_room_max_tier

Revision ID: ce261d292404
Revises: eb9f63d9a10d
Create Date: 2024-04-21 00:31:33.487275

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ce261d292404"
down_revision: Union[str, None] = "eb9f63d9a10d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("room", "max_tier")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("room", sa.Column("max_tier", sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
