"""VaultQuestLink

Revision ID: 821eb836836e
Revises: 3174081122bf
Create Date: 2024-06-15 12:14:34.236380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '821eb836836e'
down_revision: Union[str, None] = '3174081122bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vaultquestchaincompletionlink',
    sa.Column('vault_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('quest_entity_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['quest_entity_id'], ['questchain.id'], ),
    sa.ForeignKeyConstraint(['vault_id'], ['vault.id'], ),
    sa.PrimaryKeyConstraint('vault_id', 'quest_entity_id')
    )
    op.create_table('vaultquestobjectivecompletionlink',
    sa.Column('vault_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('quest_entity_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['quest_entity_id'], ['questobjective.id'], ),
    sa.ForeignKeyConstraint(['vault_id'], ['vault.id'], ),
    sa.PrimaryKeyConstraint('vault_id', 'quest_entity_id')
    )
    op.add_column('vaultquestcompletionlink', sa.Column('quest_entity_id', sqlmodel.sql.sqltypes.GUID(), nullable=False))
    op.add_column('vaultquestcompletionlink', sa.Column('is_visible', sa.Boolean(), nullable=False))
    op.drop_constraint('vaultquestcompletionlink_quest_id_fkey', 'vaultquestcompletionlink', type_='foreignkey')
    op.create_foreign_key(None, 'vaultquestcompletionlink', 'quest', ['quest_entity_id'], ['id'])
    op.drop_column('vaultquestcompletionlink', 'quest_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vaultquestcompletionlink', sa.Column('quest_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'vaultquestcompletionlink', type_='foreignkey')
    op.create_foreign_key('vaultquestcompletionlink_quest_id_fkey', 'vaultquestcompletionlink', 'quest', ['quest_id'], ['id'])
    op.drop_column('vaultquestcompletionlink', 'is_visible')
    op.drop_column('vaultquestcompletionlink', 'quest_entity_id')
    op.drop_table('vaultquestobjectivecompletionlink')
    op.drop_table('vaultquestchaincompletionlink')
    # ### end Alembic commands ###
