"""vault-defaults-storage-space

Revision ID: eb9f63d9a10d
Revises: afbb0edd3fff
Create Date: 2024-04-08 01:04:42.346323

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "eb9f63d9a10d"
down_revision: Union[str, None] = "afbb0edd3fff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("vault", sa.Column("storage_space_max", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vault", "storage_space_max")
    # ### end Alembic commands ###
