"""Add storage model for vault

Revision ID: 724d6aaa2a96
Revises: c31ab7024e6a
Create Date: 2024-05-26 23:51:36.889458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '724d6aaa2a96'
down_revision: Union[str, None] = 'c31ab7024e6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storage',
    sa.Column('used_space', sa.Integer(), nullable=False),
    sa.Column('max_space', sa.Integer(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('vault_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['vault_id'], ['vault.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storage_id'), 'storage', ['id'], unique=False)
    op.add_column('junk', sa.Column('storage_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_foreign_key(None, 'junk', 'storage', ['storage_id'], ['id'])
    op.add_column('outfit', sa.Column('storage_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_foreign_key(None, 'outfit', 'storage', ['storage_id'], ['id'])
    op.drop_column('vault', 'storage_space_max')
    op.add_column('weapon', sa.Column('storage_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_foreign_key(None, 'weapon', 'storage', ['storage_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'weapon', type_='foreignkey')
    op.drop_column('weapon', 'storage_id')
    op.add_column('vault', sa.Column('storage_space_max', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'outfit', type_='foreignkey')
    op.drop_column('outfit', 'storage_id')
    op.drop_constraint(None, 'junk', type_='foreignkey')
    op.drop_column('junk', 'storage_id')
    op.drop_index(op.f('ix_storage_id'), table_name='storage')
    op.drop_table('storage')
    # ### end Alembic commands ###
