"""dweller_optional_last_name

Revision ID: 3f616e6a53ea
Revises: 871004adaf85
Create Date: 2024-04-03 18:01:38.311602

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3f616e6a53ea"
down_revision: Union[str, None] = "871004adaf85"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("dweller", "last_name", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("dweller", "last_name", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
