"""room_update

Revision ID: 999a6f1c9001
Revises: 3f616e6a53ea
Create Date: 2024-04-05 23:46:12.030133

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "999a6f1c9001"
down_revision: Union[str, None] = "3f616e6a53ea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("room", "incremental_cost", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("room", "incremental_cost", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
