"""room_size

Revision ID: c31ab7024e6a
Revises: 5da8ad6c511e
Create Date: 2024-05-26 01:09:37.643151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c31ab7024e6a'
down_revision: Union[str, None] = '5da8ad6c511e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'size')
    # ### end Alembic commands ###
