"""VaultQuest

Revision ID: 27517367f336
Revises: 4ef1bee0b4c4
Create Date: 2024-06-15 02:04:07.152277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '27517367f336'
down_revision: Union[str, None] = '4ef1bee0b4c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vaultquestcompletionlink',
    sa.Column('vault_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('quest_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['quest_id'], ['quest.id'], ),
    sa.ForeignKeyConstraint(['vault_id'], ['vault.id'], ),
    sa.PrimaryKeyConstraint('vault_id', 'quest_id')
    )
    op.drop_column('quest', 'completed')
    op.drop_column('questchain', 'completed')
    op.drop_column('questobjective', 'completed')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questobjective', sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('questchain', sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('quest', sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_table('vaultquestcompletionlink')
    # ### end Alembic commands ###
