"""VaultQuest status

Revision ID: 3174081122bf
Revises: 27517367f336
Create Date: 2024-06-15 02:05:42.803532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3174081122bf'
down_revision: Union[str, None] = '27517367f336'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vaultquestcompletionlink', sa.Column('is_completed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vaultquestcompletionlink', 'is_completed')
    # ### end Alembic commands ###
