"""room_coords

Revision ID: afbb0edd3fff
Revises: 999a6f1c9001
Create Date: 2024-04-07 13:00:33.256218

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "afbb0edd3fff"
down_revision: Union[str, None] = "999a6f1c9001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("room", sa.Column("coordinate_x", sa.Integer(), nullable=True))
    op.add_column("room", sa.Column("coordinate_y", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("room", "coordinate_y")
    op.drop_column("room", "coordinate_x")
    # ### end Alembic commands ###
