"""dwellers additional data

Revision ID: d7d1205d632f
Revises: 8f5ca829bb79
Create Date: 2024-06-29 16:17:51.892153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd7d1205d632f'
down_revision: Union[str, None] = '8f5ca829bb79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dweller', sa.Column('visual_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('dweller', sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dweller', 'bio')
    op.drop_column('dweller', 'visual_attributes')
    # ### end Alembic commands ###
