"""thumbnail_url

Revision ID: 0f646631f7de
Revises: d7d1205d632f
Create Date: 2024-07-12 19:58:07.928253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0f646631f7de'
down_revision: Union[str, None] = 'd7d1205d632f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dweller', sa.Column('thumbnail_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dweller', 'thumbnail_url')
    # ### end Alembic commands ###
