"""initial

Revision ID: ac889cf9d7b5
Revises:
Create Date: 2024-10-18 01:44:08.431337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac889cf9d7b5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('objective',
    sa.Column('challenge', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('reward', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_objective_challenge'), 'objective', ['challenge'], unique=False)
    op.create_index(op.f('ix_objective_id'), 'objective', ['id'], unique=False)
    op.create_table('prompt',
    sa.Column('prompt_name', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('prompt_template', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_id'), 'prompt', ['id'], unique=False)
    op.create_table('quest',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('short_description', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('long_description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('requirements', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('rewards', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quest_id'), 'quest', ['id'], unique=False)
    op.create_index(op.f('ix_quest_title'), 'quest', ['title'], unique=False)
    op.create_table('user',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('llminteraction',
    sa.Column('parameters', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('response', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('usage', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prompt_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompt.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llminteraction_id'), 'llminteraction', ['id'], unique=False)
    op.create_table('vault',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('bottle_caps', sa.Integer(), nullable=False),
    sa.Column('happiness', sa.Integer(), nullable=False),
    sa.Column('power', sa.Integer(), nullable=False),
    sa.Column('power_max', sa.Integer(), nullable=False),
    sa.Column('food', sa.Integer(), nullable=False),
    sa.Column('food_max', sa.Integer(), nullable=False),
    sa.Column('water', sa.Integer(), nullable=False),
    sa.Column('water_max', sa.Integer(), nullable=False),
    sa.Column('population_max', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vault_id'), 'vault', ['id'], unique=False)
    op.create_index(op.f('ix_vault_number'), 'vault', ['number'], unique=False)
    op.create_table('room',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('category', sa.Enum('CAPACITY', 'CRAFTING', 'MISC', 'PRODUCTION', 'QUESTS', 'THEME', 'TRAINING', name='roomtypeenum'), nullable=False),
    sa.Column('ability', sa.Enum('STRENGTH', 'PERCEPTION', 'ENDURANCE', 'CHARISMA', 'INTELLIGENCE', 'AGILITY', 'LUCK', name='specialenum'), nullable=True),
    sa.Column('population_required', sa.Integer(), nullable=True),
    sa.Column('base_cost', sa.Integer(), nullable=False),
    sa.Column('incremental_cost', sa.Integer(), nullable=True),
    sa.Column('t2_upgrade_cost', sa.Integer(), nullable=True),
    sa.Column('t3_upgrade_cost', sa.Integer(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('output', sa.Integer(), nullable=True),
    sa.Column('size_min', sa.Integer(), nullable=False),
    sa.Column('size_max', sa.Integer(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('coordinate_x', sa.Integer(), nullable=True),
    sa.Column('coordinate_y', sa.Integer(), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['vault_id'], ['vault.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_id'), 'room', ['id'], unique=False)
    op.create_index(op.f('ix_room_name'), 'room', ['name'], unique=False)
    op.create_table('storage',
    sa.Column('used_space', sa.Integer(), nullable=False),
    sa.Column('max_space', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['vault_id'], ['vault.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storage_id'), 'storage', ['id'], unique=False)
    op.create_table('vaultobjectiveprogresslink',
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('objective_id', sa.Uuid(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['objective_id'], ['objective.id'], ),
    sa.ForeignKeyConstraint(['vault_id'], ['vault.id'], ),
    sa.PrimaryKeyConstraint('vault_id', 'objective_id')
    )
    op.create_table('vaultquestcompletionlink',
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('quest_id', sa.Uuid(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['quest_id'], ['quest.id'], ),
    sa.ForeignKeyConstraint(['vault_id'], ['vault.id'], ),
    sa.PrimaryKeyConstraint('vault_id', 'quest_id')
    )
    op.create_table('dweller',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('perception', sa.Integer(), nullable=False),
    sa.Column('endurance', sa.Integer(), nullable=False),
    sa.Column('charisma', sa.Integer(), nullable=False),
    sa.Column('intelligence', sa.Integer(), nullable=False),
    sa.Column('agility', sa.Integer(), nullable=False),
    sa.Column('luck', sa.Integer(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('is_adult', sa.Boolean(), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='genderenum'), nullable=False),
    sa.Column('rarity', sa.Enum('COMMON', 'RARE', 'LEGENDARY', name='rarityenum'), nullable=False),
    sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('visual_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('thumbnail_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('experience', sa.Integer(), nullable=False),
    sa.Column('max_health', sa.Integer(), nullable=False),
    sa.Column('health', sa.Integer(), nullable=False),
    sa.Column('radiation', sa.Integer(), nullable=False),
    sa.Column('happiness', sa.Integer(), nullable=False),
    sa.Column('stimpack', sa.Integer(), nullable=False),
    sa.Column('radaway', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('room_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.ForeignKeyConstraint(['vault_id'], ['vault.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dweller_first_name'), 'dweller', ['first_name'], unique=False)
    op.create_index(op.f('ix_dweller_id'), 'dweller', ['id'], unique=False)
    op.create_index(op.f('ix_dweller_last_name'), 'dweller', ['last_name'], unique=False)
    op.create_table('junk',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('rarity', sa.Enum('COMMON', 'RARE', 'LEGENDARY', name='rarityenum'), nullable=False),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('junk_type', sa.Enum('CIRCUITRY', 'LEATHER', 'ADHESIVE', 'CLOTH', 'SCIENCE', 'STEEL', 'VALUABLES', name='junktypeenum'), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('storage_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['storage_id'], ['storage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_junk_id'), 'junk', ['id'], unique=False)
    op.create_index(op.f('ix_junk_name'), 'junk', ['name'], unique=True)
    op.create_table('outfit',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('rarity', sa.Enum('COMMON', 'RARE', 'LEGENDARY', name='rarityenum'), nullable=False),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('outfit_type', sa.Enum('COMMON', 'RARE', 'LEGENDARY', 'POWER_ARMOR', 'TIERED', name='outfittypeenum'), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='genderenum'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dweller_id', sa.Uuid(), nullable=True),
    sa.Column('storage_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['dweller_id'], ['dweller.id'], ),
    sa.ForeignKeyConstraint(['storage_id'], ['storage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outfit_id'), 'outfit', ['id'], unique=False)
    op.create_index(op.f('ix_outfit_name'), 'outfit', ['name'], unique=True)
    op.create_table('weapon',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('rarity', sa.Enum('COMMON', 'RARE', 'LEGENDARY', name='rarityenum'), nullable=False),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('weapon_type', sa.Enum('MELEE', 'GUN', 'ENERGY', 'HEAVY', name='weapontypeenum'), nullable=False),
    sa.Column('weapon_subtype', sa.Enum('BLUNT', 'EDGED', 'POINTED', 'PISTOL', 'RIFLE', 'SHOTGUN', 'AUTOMATIC', 'EXPLOSIVE', 'FLAMER', name='weaponsubtypeenum'), nullable=False),
    sa.Column('stat', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('damage_min', sa.Integer(), nullable=False),
    sa.Column('damage_max', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dweller_id', sa.Uuid(), nullable=True),
    sa.Column('storage_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['dweller_id'], ['dweller.id'], ),
    sa.ForeignKeyConstraint(['storage_id'], ['storage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weapon_id'), 'weapon', ['id'], unique=False)
    op.create_index(op.f('ix_weapon_name'), 'weapon', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weapon_name'), table_name='weapon')
    op.drop_index(op.f('ix_weapon_id'), table_name='weapon')
    op.drop_table('weapon')
    op.drop_index(op.f('ix_outfit_name'), table_name='outfit')
    op.drop_index(op.f('ix_outfit_id'), table_name='outfit')
    op.drop_table('outfit')
    op.drop_index(op.f('ix_junk_name'), table_name='junk')
    op.drop_index(op.f('ix_junk_id'), table_name='junk')
    op.drop_table('junk')
    op.drop_index(op.f('ix_dweller_last_name'), table_name='dweller')
    op.drop_index(op.f('ix_dweller_id'), table_name='dweller')
    op.drop_index(op.f('ix_dweller_first_name'), table_name='dweller')
    op.drop_table('dweller')
    op.drop_table('vaultquestcompletionlink')
    op.drop_table('vaultobjectiveprogresslink')
    op.drop_index(op.f('ix_storage_id'), table_name='storage')
    op.drop_table('storage')
    op.drop_index(op.f('ix_room_name'), table_name='room')
    op.drop_index(op.f('ix_room_id'), table_name='room')
    op.drop_table('room')
    op.drop_index(op.f('ix_vault_number'), table_name='vault')
    op.drop_index(op.f('ix_vault_id'), table_name='vault')
    op.drop_table('vault')
    op.drop_index(op.f('ix_llminteraction_id'), table_name='llminteraction')
    op.drop_table('llminteraction')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_quest_title'), table_name='quest')
    op.drop_index(op.f('ix_quest_id'), table_name='quest')
    op.drop_table('quest')
    op.drop_index(op.f('ix_prompt_id'), table_name='prompt')
    op.drop_table('prompt')
    op.drop_index(op.f('ix_objective_id'), table_name='objective')
    op.drop_index(op.f('ix_objective_challenge'), table_name='objective')
    op.drop_table('objective')
    # ### end Alembic commands ###
