"""prompt-llm-interaction

Revision ID: e0f442dfc508
Revises: abe4ab4135e9
Create Date: 2024-08-12 00:02:24.843923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e0f442dfc508'
down_revision: Union[str, None] = 'abe4ab4135e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt',
    sa.Column('prompt_name', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('prompt_template', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_id'), 'prompt', ['id'], unique=False)
    op.create_table('llminteraction',
    sa.Column('parameters', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('response', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('usage', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prompt_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompt.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llminteraction_id'), 'llminteraction', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llminteraction_id'), table_name='llminteraction')
    op.drop_table('llminteraction')
    op.drop_index(op.f('ix_prompt_id'), table_name='prompt')
    op.drop_table('prompt')
    # ### end Alembic commands ###
