"""prompt

Revision ID: 23487125d425
Revises: abe4ab4135e9
Create Date: 2024-08-11 23:28:31.984502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '23487125d425'
down_revision: Union[str, None] = 'abe4ab4135e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt',
                    sa.Column('prompt_name', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
                    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
                    sa.Column('prompt_template', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
                    sa.Column('entity_id', sa.Uuid(), nullable=True),
                    sa.Column('ai_model_type', sa.Enum('CHATGPT', 'DALLE', 'OTHER', name='aimodeltype'),
                              nullable=False),
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_prompt_id'), 'prompt', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prompt_id'), table_name='prompt')
    op.drop_table('prompt')
    # ### end Alembic commands ###
