"""simplify_quests

Revision ID: a8be5a1c4017
Revises: 56c07aeccb1f
Create Date: 2024-10-12 21:09:41.338586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'a8be5a1c4017'
down_revision: Union[str, None] = '56c07aeccb1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vaultquestcompletionlink',
                  sa.Column('quest_entity_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('vaultquestcompletionlink_quest_entity_id_fkey', 'vaultquestcompletionlink', 'quest',
                          ['quest_entity_id'], ['id'])
    op.alter_column('vault', 'name',
                    existing_type=sa.Integer(),
                    type_=sa.VARCHAR(length=32),
                    existing_nullable=False)
    op.add_column('quest', sa.Column('chain_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('quest_chain_id_fkey', 'quest', 'questchain', ['chain_id'], ['id'])
    op.create_table('questchain',
                    sa.Column('title', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
                    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name='questchain_pkey'),
                    postgresql_ignore_search_path=False
                    )
    op.create_index('ix_questchain_title', 'questchain', ['title'], unique=False)
    op.create_index('ix_questchain_id', 'questchain', ['id'], unique=False)
    op.create_table('questobjective',
                    sa.Column('title', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
                    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
                    sa.Column('quest_id', sa.UUID(), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['quest_id'], ['quest.id'], name='questobjective_quest_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='questobjective_pkey'),
                    postgresql_ignore_search_path=False
                    )
    op.create_index('ix_questobjective_title', 'questobjective', ['title'], unique=False)
    op.create_index('ix_questobjective_id', 'questobjective', ['id'], unique=False)
    op.create_table('vaultquestobjectivecompletionlink',
                    sa.Column('vault_id', sa.UUID(), autoincrement=False, nullable=False),
                    sa.Column('quest_entity_id', sa.UUID(), autoincrement=False, nullable=False),
                    sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['quest_entity_id'], ['questobjective.id'],
                                            name='vaultquestobjectivecompletionlink_quest_entity_id_fkey'),
                    sa.ForeignKeyConstraint(['vault_id'], ['vault.id'],
                                            name='vaultquestobjectivecompletionlink_vault_id_fkey'),
                    sa.PrimaryKeyConstraint('vault_id', 'quest_entity_id',
                                            name='vaultquestobjectivecompletionlink_pkey')
                    )
    op.create_table('vaultquestchaincompletionlink',
                    sa.Column('vault_id', sa.UUID(), autoincrement=False, nullable=False),
                    sa.Column('quest_entity_id', sa.UUID(), autoincrement=False, nullable=False),
                    sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=False),
                    sa.Column('is_visible', sa.BOOLEAN(), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['quest_entity_id'], ['questchain.id'],
                                            name='vaultquestchaincompletionlink_quest_entity_id_fkey'),
                    sa.ForeignKeyConstraint(['vault_id'], ['vault.id'],
                                            name='vaultquestchaincompletionlink_vault_id_fkey'),
                    sa.PrimaryKeyConstraint('vault_id', 'quest_entity_id', name='vaultquestchaincompletionlink_pkey')
                    )
    # ### end Alembic commands ###
