"""add_email-verification_and_password_reset

Revision ID: fa045c06e2ae
Revises: a3ae46f91798
Create Date: 2025-12-30 13:53:05.881597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'fa045c06e2ae'
down_revision: Union[str, None] = 'a3ae46f91798'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add email verification and password reset columns to user table
    op.add_column('user', sa.Column('email_verified', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('user', sa.Column('email_verification_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('password_reset_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('password_reset_expires', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_email_verification_token'), 'user', ['email_verification_token'], unique=False)
    op.create_index(op.f('ix_user_password_reset_token'), 'user', ['password_reset_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_password_reset_token'), table_name='user')
    op.drop_index(op.f('ix_user_email_verification_token'), table_name='user')
    op.drop_column('user', 'password_reset_expires')
    op.drop_column('user', 'password_reset_token')
    op.drop_column('user', 'email_verification_token')
    op.drop_column('user', 'email_verified')
    # ### end Alembic commands ###
