"""add_exploration_table

Revision ID: 3a5f8b9c2d1e
Revises: 12ebb78d9ffd
Create Date: 2025-12-29 02:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3a5f8b9c2d1e'
down_revision: Union[str, None] = '12ebb78d9ffd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exploration',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'RECALLED', name='explorationstatus'), nullable=False),
    sa.Column('events', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('loot_collected', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dweller_strength', sa.Integer(), nullable=False),
    sa.Column('dweller_perception', sa.Integer(), nullable=False),
    sa.Column('dweller_endurance', sa.Integer(), nullable=False),
    sa.Column('dweller_charisma', sa.Integer(), nullable=False),
    sa.Column('dweller_intelligence', sa.Integer(), nullable=False),
    sa.Column('dweller_agility', sa.Integer(), nullable=False),
    sa.Column('dweller_luck', sa.Integer(), nullable=False),
    sa.Column('total_distance', sa.Integer(), nullable=False),
    sa.Column('total_caps_found', sa.Integer(), nullable=False),
    sa.Column('enemies_encountered', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('dweller_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['dweller_id'], ['dweller.id'], ),
    sa.ForeignKeyConstraint(['vault_id'], ['vault.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exploration_dweller_id'), 'exploration', ['dweller_id'], unique=False)
    op.create_index(op.f('ix_exploration_id'), 'exploration', ['id'], unique=False)
    op.create_index(op.f('ix_exploration_status'), 'exploration', ['status'], unique=False)
    op.create_index(op.f('ix_exploration_vault_id'), 'exploration', ['vault_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exploration_vault_id'), table_name='exploration')
    op.drop_index(op.f('ix_exploration_status'), table_name='exploration')
    op.drop_index(op.f('ix_exploration_id'), table_name='exploration')
    op.drop_index(op.f('ix_exploration_dweller_id'), table_name='exploration')
    op.drop_table('exploration')
    # ### end Alembic commands ###
