"""add_game_loop_tables

Revision ID: 12ebb78d9ffd
Revises: ac889cf9d7b5
Create Date: 2025-12-29 00:42:17.452339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '12ebb78d9ffd'
down_revision: Union[str, None] = 'ac889cf9d7b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gamestate',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_tick_time', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_paused', sa.Boolean(), nullable=False),
    sa.Column('total_game_time', sa.Integer(), nullable=False),
    sa.Column('paused_at', sa.DateTime(), nullable=True),
    sa.Column('resumed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['vault_id'], ['vault.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gamestate_id'), 'gamestate', ['id'], unique=False)
    op.create_index(op.f('ix_gamestate_vault_id'), 'gamestate', ['vault_id'], unique=True)
    op.create_table('incident',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('type', sa.Enum('RAIDER_ATTACK', 'RADROACH_INFESTATION', 'MOLE_RAT_ATTACK', 'DEATHCLAW_ATTACK', 'FERAL_GHOUL_ATTACK', 'FIRE', 'RADIATION_LEAK', 'ELECTRICAL_FAILURE', 'WATER_CONTAMINATION', name='incidenttype'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SPREADING', 'RESOLVED', 'FAILED', name='incidentstatus'), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('damage_dealt', sa.Integer(), nullable=False),
    sa.Column('enemies_defeated', sa.Integer(), nullable=False),
    sa.Column('loot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rooms_affected', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('spread_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('room_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.ForeignKeyConstraint(['vault_id'], ['vault.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_id'), 'incident', ['id'], unique=False)
    op.create_index(op.f('ix_incident_room_id'), 'incident', ['room_id'], unique=False)
    op.create_index(op.f('ix_incident_status'), 'incident', ['status'], unique=False)
    op.create_index(op.f('ix_incident_type'), 'incident', ['type'], unique=False)
    op.create_index(op.f('ix_incident_vault_id'), 'incident', ['vault_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incident_vault_id'), table_name='incident')
    op.drop_index(op.f('ix_incident_type'), table_name='incident')
    op.drop_index(op.f('ix_incident_status'), table_name='incident')
    op.drop_index(op.f('ix_incident_room_id'), table_name='incident')
    op.drop_index(op.f('ix_incident_id'), table_name='incident')
    op.drop_table('incident')
    op.drop_index(op.f('ix_gamestate_vault_id'), table_name='gamestate')
    op.drop_index(op.f('ix_gamestate_id'), table_name='gamestate')
    op.drop_table('gamestate')
    # ### end Alembic commands ###
