"""add_dweller_status_and_user_profile

Revision ID: 3f6b056a8b94
Revises: 3a5f8b9c2d1e
Create Date: 2025-12-30 10:45:58.211081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3f6b056a8b94'
down_revision: Union[str, None] = '3a5f8b9c2d1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create UserProfile table
    op.create_table('userprofile',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_dwellers_created', sa.Integer(), nullable=False),
    sa.Column('total_caps_earned', sa.Integer(), nullable=False),
    sa.Column('total_explorations', sa.Integer(), nullable=False),
    sa.Column('total_rooms_built', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userprofile_id'), 'userprofile', ['id'], unique=False)
    op.create_index(op.f('ix_userprofile_user_id'), 'userprofile', ['user_id'], unique=True)

    # Add dweller status column - first create enum type, then add column with default
    dweller_status_enum = postgresql.ENUM('IDLE', 'WORKING', 'EXPLORING', 'TRAINING', 'RESTING', 'DEAD', name='dwellerstatusenum', create_type=False)
    dweller_status_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('dweller', sa.Column('status', sa.Enum('IDLE', 'WORKING', 'EXPLORING', 'TRAINING', 'RESTING', 'DEAD', name='dwellerstatusenum'), server_default='IDLE', nullable=False))
    op.create_index(op.f('ix_dweller_status'), 'dweller', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dweller_status'), table_name='dweller')
    op.drop_column('dweller', 'status')

    # Drop the enum type
    dweller_status_enum = postgresql.ENUM('IDLE', 'WORKING', 'EXPLORING', 'TRAINING', 'RESTING', 'DEAD', name='dwellerstatusenum')
    dweller_status_enum.drop(op.get_bind(), checkfirst=True)

    op.drop_index(op.f('ix_userprofile_user_id'), table_name='userprofile')
    op.drop_index(op.f('ix_userprofile_id'), table_name='userprofile')
    op.drop_table('userprofile')
    # ### end Alembic commands ###
