"""add missing fk indexes

Revision ID: 2512d7563670
Revises: 510df7e3b2c5
Create Date: 2026-06-17 20:04:46.108906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2512d7563670'
down_revision: Union[str, None] = '510df7e3b2c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_dweller_room_id'), 'dweller', ['room_id'], unique=False)
    op.create_index(op.f('ix_dweller_vault_id'), 'dweller', ['vault_id'], unique=False)
    op.create_index(op.f('ix_outfit_dweller_id'), 'outfit', ['dweller_id'], unique=False)
    op.create_index(op.f('ix_pregnancy_father_id'), 'pregnancy', ['father_id'], unique=False)
    op.create_index(op.f('ix_pregnancy_mother_id'), 'pregnancy', ['mother_id'], unique=False)
    op.create_index(op.f('ix_relationship_dweller_1_id'), 'relationship', ['dweller_1_id'], unique=False)
    op.create_index(op.f('ix_relationship_dweller_2_id'), 'relationship', ['dweller_2_id'], unique=False)
    op.create_index(op.f('ix_room_vault_id'), 'room', ['vault_id'], unique=False)
    op.create_index(op.f('ix_storage_vault_id'), 'storage', ['vault_id'], unique=False)
    op.create_index(op.f('ix_vault_user_id'), 'vault', ['user_id'], unique=False)
    op.create_index(op.f('ix_weapon_dweller_id'), 'weapon', ['dweller_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weapon_dweller_id'), table_name='weapon')
    op.drop_index(op.f('ix_vault_user_id'), table_name='vault')
    op.drop_index(op.f('ix_storage_vault_id'), table_name='storage')
    op.drop_index(op.f('ix_room_vault_id'), table_name='room')
    op.drop_index(op.f('ix_relationship_dweller_2_id'), table_name='relationship')
    op.drop_index(op.f('ix_relationship_dweller_1_id'), table_name='relationship')
    op.drop_index(op.f('ix_pregnancy_mother_id'), table_name='pregnancy')
    op.drop_index(op.f('ix_pregnancy_father_id'), table_name='pregnancy')
    op.drop_index(op.f('ix_outfit_dweller_id'), table_name='outfit')
    op.drop_index(op.f('ix_dweller_vault_id'), table_name='dweller')
    op.drop_index(op.f('ix_dweller_room_id'), table_name='dweller')
    # ### end Alembic commands ###
