"""initial

Revision ID: 34f9ec11db72
Revises:
Create Date: 2026-01-08 14:55:58.879551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '34f9ec11db72'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('objective',
    sa.Column('challenge', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('reward', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_objective_challenge'), 'objective', ['challenge'], unique=False)
    op.create_index(op.f('ix_objective_id'), 'objective', ['id'], unique=False)
    op.create_table('prompt',
    sa.Column('prompt_name', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('prompt_template', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_id'), 'prompt', ['id'], unique=False)
    op.create_table('quest',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('short_description', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('long_description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('requirements', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('rewards', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quest_id'), 'quest', ['id'], unique=False)
    op.create_index(op.f('ix_quest_title'), 'quest', ['title'], unique=False)
    op.create_table('user',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verification_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('password_reset_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('password_reset_expires', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_email_verification_token'), 'user', ['email_verification_token'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_password_reset_token'), 'user', ['password_reset_token'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('llminteraction',
    sa.Column('parameters', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('response', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('usage', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prompt_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompt.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llminteraction_id'), 'llminteraction', ['id'], unique=False)
    op.create_table('userprofile',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_dwellers_created', sa.Integer(), nullable=False),
    sa.Column('total_caps_earned', sa.Integer(), nullable=False),
    sa.Column('total_explorations', sa.Integer(), nullable=False),
    sa.Column('total_rooms_built', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userprofile_id'), 'userprofile', ['id'], unique=False)
    op.create_index(op.f('ix_userprofile_user_id'), 'userprofile', ['user_id'], unique=True)
    op.create_table('vault',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('bottle_caps', sa.Integer(), nullable=False),
    sa.Column('happiness', sa.Integer(), nullable=False),
    sa.Column('power', sa.Integer(), nullable=False),
    sa.Column('power_max', sa.Integer(), nullable=False),
    sa.Column('food', sa.Integer(), nullable=False),
    sa.Column('food_max', sa.Integer(), nullable=False),
    sa.Column('water', sa.Integer(), nullable=False),
    sa.Column('water_max', sa.Integer(), nullable=False),
    sa.Column('population_max', sa.Integer(), nullable=True),
    sa.Column('radio_mode', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vault_id'), 'vault', ['id'], unique=False)
    op.create_index(op.f('ix_vault_number'), 'vault', ['number'], unique=False)
    op.create_table('gamestate',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_tick_time', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_paused', sa.Boolean(), nullable=False),
    sa.Column('total_game_time', sa.Integer(), nullable=False),
    sa.Column('paused_at', sa.DateTime(), nullable=True),
    sa.Column('resumed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['vault_id'], ['vault.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gamestate_id'), 'gamestate', ['id'], unique=False)
    op.create_index(op.f('ix_gamestate_vault_id'), 'gamestate', ['vault_id'], unique=True)
    op.create_table('room',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('category', sa.Enum('CAPACITY', 'CRAFTING', 'MISC', 'PRODUCTION', 'QUESTS', 'THEME', 'TRAINING', name='roomtypeenum'), nullable=False),
    sa.Column('ability', sa.Enum('STRENGTH', 'PERCEPTION', 'ENDURANCE', 'CHARISMA', 'INTELLIGENCE', 'AGILITY', 'LUCK', name='specialenum'), nullable=True),
    sa.Column('population_required', sa.Integer(), nullable=True),
    sa.Column('base_cost', sa.Integer(), nullable=False),
    sa.Column('incremental_cost', sa.Integer(), nullable=True),
    sa.Column('t2_upgrade_cost', sa.Integer(), nullable=True),
    sa.Column('t3_upgrade_cost', sa.Integer(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('output', sa.Integer(), nullable=True),
    sa.Column('size_min', sa.Integer(), nullable=False),
    sa.Column('size_max', sa.Integer(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('coordinate_x', sa.Integer(), nullable=True),
    sa.Column('coordinate_y', sa.Integer(), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('speedup_multiplier', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['vault_id'], ['vault.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_id'), 'room', ['id'], unique=False)
    op.create_index(op.f('ix_room_name'), 'room', ['name'], unique=False)
    op.create_table('storage',
    sa.Column('used_space', sa.Integer(), nullable=False),
    sa.Column('max_space', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['vault_id'], ['vault.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storage_id'), 'storage', ['id'], unique=False)
    op.create_table('vaultobjectiveprogresslink',
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('objective_id', sa.Uuid(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['objective_id'], ['objective.id'], ),
    sa.ForeignKeyConstraint(['vault_id'], ['vault.id'], ),
    sa.PrimaryKeyConstraint('vault_id', 'objective_id')
    )
    op.create_table('vaultquestcompletionlink',
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('quest_id', sa.Uuid(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['quest_id'], ['quest.id'], ),
    sa.ForeignKeyConstraint(['vault_id'], ['vault.id'], ),
    sa.PrimaryKeyConstraint('vault_id', 'quest_id')
    )
    op.create_table('dweller',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('perception', sa.Integer(), nullable=False),
    sa.Column('endurance', sa.Integer(), nullable=False),
    sa.Column('charisma', sa.Integer(), nullable=False),
    sa.Column('intelligence', sa.Integer(), nullable=False),
    sa.Column('agility', sa.Integer(), nullable=False),
    sa.Column('luck', sa.Integer(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('is_adult', sa.Boolean(), nullable=False),
    sa.Column('age_group', sa.Enum('CHILD', 'TEEN', 'ADULT', name='agegroupenum'), nullable=False),
    sa.Column('birth_date', sa.DateTime(), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='genderenum'), nullable=False),
    sa.Column('rarity', sa.Enum('COMMON', 'RARE', 'LEGENDARY', name='rarityenum'), nullable=False),
    sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('visual_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('thumbnail_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('experience', sa.Integer(), nullable=False),
    sa.Column('max_health', sa.Integer(), nullable=False),
    sa.Column('health', sa.Integer(), nullable=False),
    sa.Column('radiation', sa.Integer(), nullable=False),
    sa.Column('happiness', sa.Integer(), nullable=False),
    sa.Column('stimpack', sa.Integer(), nullable=False),
    sa.Column('radaway', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('IDLE', 'WORKING', 'EXPLORING', 'TRAINING', 'RESTING', 'DEAD', name='dwellerstatusenum'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('room_id', sa.Uuid(), nullable=True),
    sa.Column('partner_id', sa.UUID(), nullable=True),
    sa.Column('parent_1_id', sa.UUID(), nullable=True),
    sa.Column('parent_2_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['parent_1_id'], ['dweller.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_2_id'], ['dweller.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['partner_id'], ['dweller.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vault_id'], ['vault.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dweller_first_name'), 'dweller', ['first_name'], unique=False)
    op.create_index(op.f('ix_dweller_id'), 'dweller', ['id'], unique=False)
    op.create_index(op.f('ix_dweller_last_name'), 'dweller', ['last_name'], unique=False)
    op.create_index(op.f('ix_dweller_status'), 'dweller', ['status'], unique=False)
    op.create_table('incident',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('type', sa.Enum('RAIDER_ATTACK', 'RADROACH_INFESTATION', 'MOLE_RAT_ATTACK', 'DEATHCLAW_ATTACK', 'FERAL_GHOUL_ATTACK', 'FIRE', name='incidenttype'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SPREADING', 'RESOLVED', 'FAILED', name='incidentstatus'), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('damage_dealt', sa.Integer(), nullable=False),
    sa.Column('enemies_defeated', sa.Integer(), nullable=False),
    sa.Column('loot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rooms_affected', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('spread_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('room_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vault_id'], ['vault.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_id'), 'incident', ['id'], unique=False)
    op.create_index(op.f('ix_incident_room_id'), 'incident', ['room_id'], unique=False)
    op.create_index(op.f('ix_incident_status'), 'incident', ['status'], unique=False)
    op.create_index(op.f('ix_incident_type'), 'incident', ['type'], unique=False)
    op.create_index(op.f('ix_incident_vault_id'), 'incident', ['vault_id'], unique=False)
    op.create_table('junk',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('rarity', sa.Enum('COMMON', 'RARE', 'LEGENDARY', name='rarityenum'), nullable=False),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('junk_type', sa.Enum('CIRCUITRY', 'LEATHER', 'ADHESIVE', 'CLOTH', 'SCIENCE', 'STEEL', 'VALUABLES', name='junktypeenum'), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('storage_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['storage_id'], ['storage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_junk_id'), 'junk', ['id'], unique=False)
    op.create_index(op.f('ix_junk_name'), 'junk', ['name'], unique=True)
    op.create_table('chatmessage',
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('from_user_id', sa.Uuid(), nullable=True),
    sa.Column('from_dweller_id', sa.Uuid(), nullable=True),
    sa.Column('to_user_id', sa.Uuid(), nullable=True),
    sa.Column('to_dweller_id', sa.Uuid(), nullable=True),
    sa.Column('message_text', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('llm_interaction_id', sa.Uuid(), nullable=True),
    sa.Column('audio_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('transcription', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('audio_duration', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['from_dweller_id'], ['dweller.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_user_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['llm_interaction_id'], ['llminteraction.id'], ),
    sa.ForeignKeyConstraint(['to_dweller_id'], ['dweller.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_user_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vault_id'], ['vault.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatmessage_created_at'), 'chatmessage', ['created_at'], unique=False)
    op.create_index(op.f('ix_chatmessage_from_dweller_id'), 'chatmessage', ['from_dweller_id'], unique=False)
    op.create_index(op.f('ix_chatmessage_from_user_id'), 'chatmessage', ['from_user_id'], unique=False)
    op.create_index(op.f('ix_chatmessage_id'), 'chatmessage', ['id'], unique=False)
    op.create_index(op.f('ix_chatmessage_to_dweller_id'), 'chatmessage', ['to_dweller_id'], unique=False)
    op.create_index(op.f('ix_chatmessage_to_user_id'), 'chatmessage', ['to_user_id'], unique=False)
    op.create_index(op.f('ix_chatmessage_vault_id'), 'chatmessage', ['vault_id'], unique=False)
    op.create_table('exploration',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'RECALLED', name='explorationstatus'), nullable=False),
    sa.Column('events', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('loot_collected', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dweller_strength', sa.Integer(), nullable=False),
    sa.Column('dweller_perception', sa.Integer(), nullable=False),
    sa.Column('dweller_endurance', sa.Integer(), nullable=False),
    sa.Column('dweller_charisma', sa.Integer(), nullable=False),
    sa.Column('dweller_intelligence', sa.Integer(), nullable=False),
    sa.Column('dweller_agility', sa.Integer(), nullable=False),
    sa.Column('dweller_luck', sa.Integer(), nullable=False),
    sa.Column('total_distance', sa.Integer(), nullable=False),
    sa.Column('total_caps_found', sa.Integer(), nullable=False),
    sa.Column('enemies_encountered', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('dweller_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['dweller_id'], ['dweller.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vault_id'], ['vault.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exploration_dweller_id'), 'exploration', ['dweller_id'], unique=False)
    op.create_index(op.f('ix_exploration_id'), 'exploration', ['id'], unique=False)
    op.create_index(op.f('ix_exploration_status'), 'exploration', ['status'], unique=False)
    op.create_index(op.f('ix_exploration_vault_id'), 'exploration', ['vault_id'], unique=False)
    op.create_table('notification',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=True),
    sa.Column('from_dweller_id', sa.Uuid(), nullable=True),
    sa.Column('notification_type', sa.Enum('EXPLORATION_UPDATE', 'EXPLORATION_COMPLETE', 'LEVEL_UP', 'TRAINING_COMPLETE', 'TRAINING_STARTED', 'RELATIONSHIP_FORMED', 'PREGNANCY_DETECTED', 'BABY_BORN', 'COMBAT_STARTED', 'COMBAT_VICTORY', 'COMBAT_DEFEAT', 'DWELLER_INJURED', 'RESOURCE_LOW', 'RESOURCE_CRITICAL', 'POWER_OUTAGE', 'QUEST_COMPLETE', 'ACHIEVEMENT_UNLOCKED', 'RADIO_NEW_DWELLER', name='notificationtype'), nullable=False),
    sa.Column('priority', sa.Enum('INFO', 'NORMAL', 'HIGH', 'URGENT', name='notificationpriority'), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_dismissed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_dweller_id'], ['dweller.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['vault_id'], ['vault.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_created_at'), 'notification', ['created_at'], unique=False)
    op.create_index(op.f('ix_notification_from_dweller_id'), 'notification', ['from_dweller_id'], unique=False)
    op.create_index(op.f('ix_notification_id'), 'notification', ['id'], unique=False)
    op.create_index(op.f('ix_notification_is_dismissed'), 'notification', ['is_dismissed'], unique=False)
    op.create_index(op.f('ix_notification_is_read'), 'notification', ['is_read'], unique=False)
    op.create_index(op.f('ix_notification_notification_type'), 'notification', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notification_priority'), 'notification', ['priority'], unique=False)
    op.create_index(op.f('ix_notification_user_id'), 'notification', ['user_id'], unique=False)
    op.create_index(op.f('ix_notification_vault_id'), 'notification', ['vault_id'], unique=False)
    op.create_table('outfit',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('rarity', sa.Enum('COMMON', 'RARE', 'LEGENDARY', name='rarityenum'), nullable=False),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('outfit_type', sa.Enum('COMMON', 'RARE', 'LEGENDARY', 'POWER_ARMOR', 'TIERED', name='outfittypeenum'), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='genderenum'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dweller_id', sa.Uuid(), nullable=True),
    sa.Column('storage_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['dweller_id'], ['dweller.id'], ),
    sa.ForeignKeyConstraint(['storage_id'], ['storage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outfit_id'), 'outfit', ['id'], unique=False)
    op.create_index(op.f('ix_outfit_name'), 'outfit', ['name'], unique=True)
    op.create_table('pregnancy',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('mother_id', sa.UUID(), nullable=True),
    sa.Column('father_id', sa.UUID(), nullable=True),
    sa.Column('conceived_at', sa.DateTime(), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PREGNANT', 'DELIVERED', 'MISCARRIED', name='pregnancystatusenum'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['father_id'], ['dweller.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mother_id'], ['dweller.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pregnancy_id'), 'pregnancy', ['id'], unique=False)
    op.create_table('relationship',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('dweller_1_id', sa.UUID(), nullable=True),
    sa.Column('dweller_2_id', sa.UUID(), nullable=True),
    sa.Column('relationship_type', sa.Enum('ACQUAINTANCE', 'FRIEND', 'ROMANTIC', 'PARTNER', 'EX', name='relationshiptypeenum'), nullable=False),
    sa.Column('affinity', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['dweller_1_id'], ['dweller.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dweller_2_id'], ['dweller.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relationship_id'), 'relationship', ['id'], unique=False)
    op.create_table('training',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('dweller_id', sa.Uuid(), nullable=False),
    sa.Column('room_id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('stat_being_trained', sa.Enum('STRENGTH', 'PERCEPTION', 'ENDURANCE', 'CHARISMA', 'INTELLIGENCE', 'AGILITY', 'LUCK', name='specialenum'), nullable=False),
    sa.Column('current_stat_value', sa.Integer(), nullable=False),
    sa.Column('target_stat_value', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('estimated_completion_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'CANCELLED', name='trainingstatus'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['dweller_id'], ['dweller.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.ForeignKeyConstraint(['vault_id'], ['vault.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_dweller_id'), 'training', ['dweller_id'], unique=False)
    op.create_index(op.f('ix_training_id'), 'training', ['id'], unique=False)
    op.create_index(op.f('ix_training_room_id'), 'training', ['room_id'], unique=False)
    op.create_index(op.f('ix_training_status'), 'training', ['status'], unique=False)
    op.create_index(op.f('ix_training_vault_id'), 'training', ['vault_id'], unique=False)
    op.create_table('weapon',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('rarity', sa.Enum('COMMON', 'RARE', 'LEGENDARY', name='rarityenum'), nullable=False),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('weapon_type', sa.Enum('MELEE', 'GUN', 'ENERGY', 'HEAVY', name='weapontypeenum'), nullable=False),
    sa.Column('weapon_subtype', sa.Enum('BLUNT', 'EDGED', 'POINTED', 'PISTOL', 'RIFLE', 'SHOTGUN', 'AUTOMATIC', 'EXPLOSIVE', 'FLAMER', name='weaponsubtypeenum'), nullable=False),
    sa.Column('stat', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('damage_min', sa.Integer(), nullable=False),
    sa.Column('damage_max', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dweller_id', sa.Uuid(), nullable=True),
    sa.Column('storage_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['dweller_id'], ['dweller.id'], ),
    sa.ForeignKeyConstraint(['storage_id'], ['storage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weapon_id'), 'weapon', ['id'], unique=False)
    op.create_index(op.f('ix_weapon_name'), 'weapon', ['name'], unique=True)

    # Seed initial data
    from app.core.security import get_password_hash
    from datetime import datetime, timezone
    import uuid
    import os

    conn = op.get_bind()

    # Get settings from environment
    admin_username = os.getenv('FIRST_SUPERUSER_USERNAME', 'admin')
    admin_password = os.getenv('FIRST_SUPERUSER_PASSWORD', 'admin')
    admin_email = os.getenv('FIRST_SUPERUSER_EMAIL', 'admin@example.com')
    test_email = os.getenv('EMAIL_TEST_USER', 'test@example.com')

    admin_id = str(uuid.uuid4())
    admin_hashed = get_password_hash(admin_password)
    test_id = str(uuid.uuid4())
    test_hashed = get_password_hash('testpassword')
    now = datetime.now()

    # Insert admin user
    conn.execute(
        sa.text("""
            INSERT INTO "user" (id, username, email, hashed_password, is_superuser, is_active, email_verified, created_at, updated_at)
            VALUES (:id, :username, :email, :password, true, true, true, :now, :now)
        """),
        {"id": admin_id, "username": admin_username, "email": admin_email, "password": admin_hashed, "now": now}
    )

    # Insert test user
    conn.execute(
        sa.text("""
            INSERT INTO "user" (id, username, email, hashed_password, is_superuser, is_active, email_verified, created_at, updated_at)
            VALUES (:id, 'TestUser', :email, :password, false, true, true, :now, :now)
        """),
        {"id": test_id, "email": test_email, "password": test_hashed, "now": now}
    )

    # Create test vault
    vault_id = str(uuid.uuid4())
    conn.execute(
        sa.text("""
            INSERT INTO vault (id, number, bottle_caps, happiness, power, power_max, food, food_max, water, water_max, population_max, radio_mode, user_id, created_at, updated_at)
            VALUES (:id, 101, 1000, 50, 50, 100, 100, 200, 100, 200, 200, 'recruitment', :user_id, :now, :now)
        """),
        {"id": vault_id, "user_id": test_id, "now": now}
    )

    print("Initial users and vault created")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('celery_intervalschedule',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('every', sa.INTEGER(), autoincrement=False, nullable=False, comment='Number of interval periods to wait before running the task again'),
    sa.Column('period', postgresql.ENUM('days', 'hours', 'minutes', 'seconds', 'microseconds', name='period'), autoincrement=False, nullable=False, comment='The type of period between task runs (Example: days)'),
    sa.CheckConstraint('every >= 1', name=op.f('celery_intervalschedule_every_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('celery_intervalschedule_pkey'))
    )
    op.create_table('celery_clockedschedule',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('clocked_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('celery_clockedschedule_pkey'))
    )
    op.create_table('celery_periodictaskchanged',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('last_update', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('celery_periodictaskchanged_pkey'))
    )
    op.create_table('celery_periodictask',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='Short Description For This Task'),
    sa.Column('task', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='The Name of the Celery Task that Should be Run.  (Example: "proj.tasks.import_contacts")'),
    sa.Column('args', sa.TEXT(), autoincrement=False, nullable=False, comment='JSON encoded positional arguments (Example: ["arg1", "arg2"])'),
    sa.Column('kwargs', sa.TEXT(), autoincrement=False, nullable=False, comment='JSON encoded keyword arguments (Example: {"argument": "value"})'),
    sa.Column('queue', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='Queue defined in CELERY_TASK_QUEUES. Leave None for default queuing.'),
    sa.Column('exchange', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='Override Exchange for low-level AMQP routing'),
    sa.Column('routing_key', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='Override Routing Key for low-level AMQP routing'),
    sa.Column('headers', sa.TEXT(), autoincrement=False, nullable=True, comment='JSON encoded message headers for the AMQP message.'),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=True, comment='Priority Number between 0 and 255. Supported by: RabbitMQ, Redis (priority reversed, 0 is highest).'),
    sa.Column('expires', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='Datetime after which the schedule will no longer trigger the task to run'),
    sa.Column('expire_seconds', sa.INTEGER(), autoincrement=False, nullable=True, comment='Timedelta with seconds which the schedule will no longer trigger the task to run'),
    sa.Column('one_off', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='If True, the schedule will only run the task a single time'),
    sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='Datetime when the schedule should begin triggering the task to run'),
    sa.Column('enabled', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Set to False to disable the schedule'),
    sa.Column('last_run_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='Datetime that the schedule last triggered the task to run. '),
    sa.Column('total_run_count', sa.INTEGER(), autoincrement=False, nullable=False, comment='Running count of how many times the schedule has triggered the task'),
    sa.Column('date_changed', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='Datetime that this PeriodicTask was last modified'),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True, comment='Detailed description about the details of this Periodic Task'),
    sa.Column('discriminator', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment='Lower case name of the schedule class. '),
    sa.Column('schedule_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='ID of the schedule model object. '),
    sa.CheckConstraint('priority >= 0 AND priority <= 255', name=op.f('celery_periodictask_priority_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('celery_periodictask_pkey')),
    sa.UniqueConstraint('name', name=op.f('celery_periodictask_name_key'))
    )
    op.create_table('celery_solarschedule',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event', postgresql.ENUM('dawn_astronomical', 'dawn_nautical', 'dawn_civil', 'sunrise', 'solar_noon', 'sunset', 'dusk_civil', 'dusk_nautical', 'dusk_astronomical', name='solarevent'), autoincrement=False, nullable=False, comment='The type of solar event when the job should run'),
    sa.Column('latitude', sa.NUMERIC(precision=9, scale=6), autoincrement=False, nullable=False, comment='Run the task when the event happens at this latitude'),
    sa.Column('longitude', sa.NUMERIC(precision=9, scale=6), autoincrement=False, nullable=False, comment='Run the task when the event happens at this longitude'),
    sa.CheckConstraint("latitude >= '-90'::integer::numeric AND latitude <= 90::numeric", name=op.f('celery_solarschedule_latitude_check')),
    sa.CheckConstraint("longitude >= '-180'::integer::numeric AND longitude <= 180::numeric", name=op.f('celery_solarschedule_longitude_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('celery_solarschedule_pkey')),
    sa.UniqueConstraint('event', 'latitude', 'longitude', name=op.f('celery_solarschedule_event_latitude_longitude_key'))
    )
    op.create_table('celery_crontabschedule',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('minute', sa.VARCHAR(length=240), autoincrement=False, nullable=False, comment='Cron Minutes to Run. Use "*" for "all". (Example: "0,30")'),
    sa.Column('hour', sa.VARCHAR(length=96), autoincrement=False, nullable=False, comment='Cron Hours to Run. Use "*" for "all". (Example: "8,20")'),
    sa.Column('day_of_week', sa.VARCHAR(length=64), autoincrement=False, nullable=False, comment='Cron Days Of The Week to Run. Use "*" for "all", Sunday is 0 or 7, Monday is 1. (Example: "0,5")'),
    sa.Column('day_of_month', sa.VARCHAR(length=124), autoincrement=False, nullable=False, comment='Cron Days Of The Month to Run. Use "*" for "all". (Example: "1,15")'),
    sa.Column('month_of_year', sa.VARCHAR(length=64), autoincrement=False, nullable=False, comment='Cron Months (1-12) Of The Year to Run. Use "*" for "all". (Example: "1,12")'),
    sa.Column('timezone', sa.VARCHAR(length=64), autoincrement=False, nullable=False, comment='Timezone to Run the Cron Schedule on. Default is UTC.'),
    sa.PrimaryKeyConstraint('id', name=op.f('celery_crontabschedule_pkey'))
    )
    op.drop_index(op.f('ix_weapon_name'), table_name='weapon')
    op.drop_index(op.f('ix_weapon_id'), table_name='weapon')
    op.drop_table('weapon')
    op.drop_index(op.f('ix_training_vault_id'), table_name='training')
    op.drop_index(op.f('ix_training_status'), table_name='training')
    op.drop_index(op.f('ix_training_room_id'), table_name='training')
    op.drop_index(op.f('ix_training_id'), table_name='training')
    op.drop_index(op.f('ix_training_dweller_id'), table_name='training')
    op.drop_table('training')
    op.drop_index(op.f('ix_relationship_id'), table_name='relationship')
    op.drop_table('relationship')
    op.drop_index(op.f('ix_pregnancy_id'), table_name='pregnancy')
    op.drop_table('pregnancy')
    op.drop_index(op.f('ix_outfit_name'), table_name='outfit')
    op.drop_index(op.f('ix_outfit_id'), table_name='outfit')
    op.drop_table('outfit')
    op.drop_index(op.f('ix_notification_vault_id'), table_name='notification')
    op.drop_index(op.f('ix_notification_user_id'), table_name='notification')
    op.drop_index(op.f('ix_notification_priority'), table_name='notification')
    op.drop_index(op.f('ix_notification_notification_type'), table_name='notification')
    op.drop_index(op.f('ix_notification_is_read'), table_name='notification')
    op.drop_index(op.f('ix_notification_is_dismissed'), table_name='notification')
    op.drop_index(op.f('ix_notification_id'), table_name='notification')
    op.drop_index(op.f('ix_notification_from_dweller_id'), table_name='notification')
    op.drop_index(op.f('ix_notification_created_at'), table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_exploration_vault_id'), table_name='exploration')
    op.drop_index(op.f('ix_exploration_status'), table_name='exploration')
    op.drop_index(op.f('ix_exploration_id'), table_name='exploration')
    op.drop_index(op.f('ix_exploration_dweller_id'), table_name='exploration')
    op.drop_table('exploration')
    op.drop_index(op.f('ix_chatmessage_vault_id'), table_name='chatmessage')
    op.drop_index(op.f('ix_chatmessage_to_user_id'), table_name='chatmessage')
    op.drop_index(op.f('ix_chatmessage_to_dweller_id'), table_name='chatmessage')
    op.drop_index(op.f('ix_chatmessage_id'), table_name='chatmessage')
    op.drop_index(op.f('ix_chatmessage_from_user_id'), table_name='chatmessage')
    op.drop_index(op.f('ix_chatmessage_from_dweller_id'), table_name='chatmessage')
    op.drop_index(op.f('ix_chatmessage_created_at'), table_name='chatmessage')
    op.drop_table('chatmessage')
    op.drop_index(op.f('ix_junk_name'), table_name='junk')
    op.drop_index(op.f('ix_junk_id'), table_name='junk')
    op.drop_table('junk')
    op.drop_index(op.f('ix_incident_vault_id'), table_name='incident')
    op.drop_index(op.f('ix_incident_type'), table_name='incident')
    op.drop_index(op.f('ix_incident_status'), table_name='incident')
    op.drop_index(op.f('ix_incident_room_id'), table_name='incident')
    op.drop_index(op.f('ix_incident_id'), table_name='incident')
    op.drop_table('incident')
    op.drop_index(op.f('ix_dweller_status'), table_name='dweller')
    op.drop_index(op.f('ix_dweller_last_name'), table_name='dweller')
    op.drop_index(op.f('ix_dweller_id'), table_name='dweller')
    op.drop_index(op.f('ix_dweller_first_name'), table_name='dweller')
    op.drop_table('dweller')
    op.drop_table('vaultquestcompletionlink')
    op.drop_table('vaultobjectiveprogresslink')
    op.drop_index(op.f('ix_storage_id'), table_name='storage')
    op.drop_table('storage')
    op.drop_index(op.f('ix_room_name'), table_name='room')
    op.drop_index(op.f('ix_room_id'), table_name='room')
    op.drop_table('room')
    op.drop_index(op.f('ix_gamestate_vault_id'), table_name='gamestate')
    op.drop_index(op.f('ix_gamestate_id'), table_name='gamestate')
    op.drop_table('gamestate')
    op.drop_index(op.f('ix_vault_number'), table_name='vault')
    op.drop_index(op.f('ix_vault_id'), table_name='vault')
    op.drop_table('vault')
    op.drop_index(op.f('ix_userprofile_user_id'), table_name='userprofile')
    op.drop_index(op.f('ix_userprofile_id'), table_name='userprofile')
    op.drop_table('userprofile')
    op.drop_index(op.f('ix_llminteraction_id'), table_name='llminteraction')
    op.drop_table('llminteraction')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_password_reset_token'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email_verification_token'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_quest_title'), table_name='quest')
    op.drop_index(op.f('ix_quest_id'), table_name='quest')
    op.drop_table('quest')
    op.drop_index(op.f('ix_prompt_id'), table_name='prompt')
    op.drop_table('prompt')
    op.drop_index(op.f('ix_objective_id'), table_name='objective')
    op.drop_index(op.f('ix_objective_challenge'), table_name='objective')
    op.drop_table('objective')
    # ### end Alembic commands ###
