"""radio_mode

Revision ID: c709889b3b11
Revises: a1b2c3d4e5f6
Create Date: 2026-01-01 19:18:53.720932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c709889b3b11'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add speedup_multiplier with default value of 1.0
    op.add_column('room', sa.Column('speedup_multiplier', sa.Float(), nullable=False, server_default='1.0'))

    # Add radio_mode column
    # Using VARCHAR for better compatibility across databases
    # Default to 'recruitment' (lowercase, matching the StrEnum value)
    op.add_column('vault', sa.Column('radio_mode', sa.VARCHAR(length=50), nullable=True))

    # Set default value for existing records
    op.execute("UPDATE vault SET radio_mode = 'recruitment' WHERE radio_mode IS NULL")

    # Make column non-nullable after setting defaults
    with op.batch_alter_table('vault') as batch_op:
        batch_op.alter_column('radio_mode', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vault', 'radio_mode')
    op.drop_column('room', 'speedup_multiplier')
    # ### end Alembic commands ###
