"""add_last_activity_time_to_game_state

Revision ID: dc587b1ae37a
Revises: fbbe3712457d
Create Date: 2026-02-02 01:22:26.141345

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "dc587b1ae37a"
down_revision: Union[str, None] = "fbbe3712457d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("gamestate", sa.Column("last_activity_time", sa.DateTime(), nullable=True))
    # Set default value for existing rows to last_tick_time
    op.execute("UPDATE gamestate SET last_activity_time = last_tick_time WHERE last_activity_time IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("gamestate", "last_activity_time")
    # ### end Alembic commands ###
