"""add_cascade_delete_to_all_foreign_keys

Revision ID: 5b4c07ac82f0
Revises: 798db1148b94
Create Date: 2026-01-06 09:54:46.434390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b4c07ac82f0'
down_revision: Union[str, None] = '798db1148b94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('exploration_vault_id_fkey'), 'exploration', type_='foreignkey')
    op.drop_constraint(op.f('exploration_dweller_id_fkey'), 'exploration', type_='foreignkey')
    op.create_foreign_key(None, 'exploration', 'vault', ['vault_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'exploration', 'dweller', ['dweller_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
