"""add_last_activity_time_to_game_state

Revision ID: dc587b1ae37a
Revises: fbbe3712457d
Create Date: 2026-02-02 01:22:26.141345

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "dc587b1ae37a"
down_revision: Union[str, None] = "fbbe3712457d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column with server_default for non-nullable constraint during creation
    op.add_column(
        "gamestate",
        sa.Column("last_activity_time", sa.DateTime(), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")),
    )
    # Update existing rows to use last_tick_time instead of current timestamp
    op.execute("UPDATE gamestate SET last_activity_time = last_tick_time")
    # Remove server_default since we handle it in application code
    op.alter_column("gamestate", "last_activity_time", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("gamestate", "last_activity_time")
    # ### end Alembic commands ###
