"""Fix foreign key constraints for dweller relationships

Adds ondelete behavior to foreign keys that reference dwellers to prevent
constraint violations when deleting dwellers.

Revision ID: 51ec51a1cb9c
Revises: ecdc11728074
Create Date: 2026-01-02 18:54:54.046923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '51ec51a1cb9c'
down_revision: Union[str, None] = 'ecdc11728074'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Update dweller self-referencing foreign keys to SET NULL on delete
    op.drop_constraint(op.f('dweller_partner_id_fkey'), 'dweller', type_='foreignkey')
    op.drop_constraint(op.f('dweller_parent_2_id_fkey'), 'dweller', type_='foreignkey')
    op.drop_constraint(op.f('dweller_parent_1_id_fkey'), 'dweller', type_='foreignkey')
    op.create_foreign_key(None, 'dweller', 'dweller', ['partner_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'dweller', 'dweller', ['parent_2_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'dweller', 'dweller', ['parent_1_id'], ['id'], ondelete='SET NULL')

    # Update relationship foreign keys to CASCADE on delete
    op.drop_constraint('relationship_dweller_1_id_fkey', 'relationship', type_='foreignkey')
    op.drop_constraint('relationship_dweller_2_id_fkey', 'relationship', type_='foreignkey')
    op.create_foreign_key(None, 'relationship', 'dweller', ['dweller_1_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'relationship', 'dweller', ['dweller_2_id'], ['id'], ondelete='CASCADE')

    # Update pregnancy foreign keys to CASCADE on delete
    op.drop_constraint('pregnancy_mother_id_fkey', 'pregnancy', type_='foreignkey')
    op.drop_constraint('pregnancy_father_id_fkey', 'pregnancy', type_='foreignkey')
    op.create_foreign_key(None, 'pregnancy', 'dweller', ['mother_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'pregnancy', 'dweller', ['father_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Downgrade may fail if constraint names have changed
    # In production, consider keeping the new constraints
    pass
    # ### end Alembic commands ###
