"""Add stimpaks and radaways to exploration

Revision ID: c7756d4e7543
Revises: 8c8003fe468d
Create Date: 2026-01-25 21:03:39.296502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c7756d4e7543'
down_revision: Union[str, None] = '8c8003fe468d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Removed auto-generated drops for Celery tables which are not managed by this migration.
    op.add_column('exploration', sa.Column('stimpaks', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('exploration', sa.Column('radaways', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exploration', 'radaways')
    op.drop_column('exploration', 'stimpaks')
    # Note: Removed auto-generated creates for Celery tables which are not managed by this migration.
    # ### end Alembic commands ###
