"""add_cascade_delete_to_all_foreign_keys

Revision ID: 798db1148b94
Revises: 9a28b3c0e741
Create Date: 2026-01-06 09:51:37.066084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '798db1148b94'
down_revision: Union[str, None] = '9a28b3c0e741'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('gamestate_vault_id_fkey'), 'gamestate', type_='foreignkey')
    op.create_foreign_key(None, 'gamestate', 'vault', ['vault_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'gamestate', type_='foreignkey')
    op.create_foreign_key(op.f('gamestate_vault_id_fkey'), 'gamestate', 'vault', ['vault_id'], ['id'])
    # ### end Alembic commands ###
