"""Preset archetypes for quick character generation."""

from app.options.factions import FactionOption
from app.options.races import RaceOption

# Archetype presets with default values for quick character creation
archetypes: dict[str, dict] = {
    "Vault Dweller": {
        "race": RaceOption.HUMAN,
        "faction": FactionOption.VAULT_DWELLER,
        "skin_tone": "Fair",
        "build": "Athletic",
        "hair_style": "Ponytail",
        "headgear": "None",
        "outfit": "Blue Vault Suit",
        "weapon": "10mm Pistol",
        "pose": "Standing confidently",
        "background": "Vault Interior",
    },
    "Brotherhood Knight": {
        "race": RaceOption.HUMAN,
        "faction": FactionOption.BROTHERHOOD_OF_STEEL,
        "skin_tone": "Tan",
        "build": "Muscular",
        "hair_style": "Buzz Cut",
        "headgear": "Combat Helmet",
        "outfit": "Power Armor T-51",
        "weapon": "Laser Rifle",
        "pose": "Power armor stance",
        "background": "Brotherhood Airship",
    },
    "Enclave Soldier": {
        "race": RaceOption.HUMAN,
        "faction": FactionOption.ENCLAVE,
        "skin_tone": "Fair",
        "build": "Athletic",
        "hair_style": "Buzz Cut",
        "headgear": "Combat Helmet",
        "outfit": "Power Armor X-01",
        "weapon": "Plasma Rifle",
        "pose": "Weapon drawn",
        "background": "Pre-War Suburb",
    },
    "Raider Warlord": {
        "race": RaceOption.HUMAN,
        "faction": FactionOption.RAIDERS,
        "skin_tone": "Tan",
        "build": "Muscular",
        "hair_style": "Mohawk",
        "headgear": "Raider Cage Mask",
        "outfit": "Spike Armor",
        "weapon": "Flamer",
        "pose": "Alert and wary",
        "background": "Wasteland Ruins",
    },
    "Super Mutant Brute": {
        "race": RaceOption.SUPER_MUTANT,
        "faction": FactionOption.SUPER_MUTANT_TRIBE,
        "skin_tone": "Green",
        "build": "Brutish",
        "hair_style": "Bald",
        "headgear": "None",
        "outfit": "Super Mutant Harness",
        "weapon": "Super Sledge",
        "pose": "Action shot",
        "background": "Super Mutant Camp",
    },
    "Institute Courser": {
        "race": RaceOption.SYNTH,
        "faction": FactionOption.THE_INSTITUTE,
        "skin_tone": "Synthetic Fair",
        "build": "Muscular",
        "hair_style": "Clean Cut",
        "headgear": "None",
        "outfit": "Synth Uniform",
        "weapon": "Institute Laser Pistol",
        "pose": "Stealth crouch",
        "background": "The Institute",
    },
    "NCR Ranger": {
        "race": RaceOption.HUMAN,
        "faction": FactionOption.NCR,
        "skin_tone": "Brown",
        "build": "Athletic",
        "hair_style": "Short Hair",
        "headgear": "Combat Helmet",
        "outfit": "NCR Ranger Combat Armor",
        "weapon": "Ranger Sequoia",
        "pose": "Weapon drawn",
        "background": "New Vegas Strip",
    },
    "Ghoul Mercenary": {
        "race": RaceOption.GHOUL,
        "faction": FactionOption.NONE,
        "skin_tone": "Mottled",
        "build": "Withered",
        "hair_style": "Patchy Hair",
        "headgear": "Scrapped Metal Helmet",
        "outfit": "Combat Armor",
        "weapon": "Hunting Rifle",
        "pose": "Alert and wary",
        "background": "Nuclear Crater",
    },
    "Children of Atom Zealot": {
        "race": RaceOption.HUMAN,
        "faction": FactionOption.CHILDREN_OF_ATOM,
        "skin_tone": "Pale",
        "build": "Slim",
        "hair_style": "Buzz Cut",
        "headgear": "Gas Mask",
        "outfit": "Rags of the Children of Atom",
        "weapon": "Gamma Gun",
        "pose": "Meditating/praying",
        "background": "Nuclear Crater",
    },
}
